const axios = require('axios');
const fs = require('fs');
let txt_str = "";

async function geocode(name) {
    try {
        await axios.get('https://maps.googleapis.com/maps/api/geocode/json', {
            params: {
                address: name,
                key: 'AIzaSyBhcNo_EDGsF_lGfThVgAVtweh_DlciUCQ'
            }
        })
        .then(function(response) {
            let lat = response.data.results[0].geometry.location.lat;
            let lng = response.data.results[0].geometry.location.lng;
            let latLngOutput = '\n' + name + "," + lat + "," + lng;
            txt_str += latLngOutput;
        })
    } catch (err) {
        console.log(err);
    }
    return;
}

let nameArray = [`Blue Springs State Park`,
`Buck's Pocket State Park`,
`Cathedral Caverns State Park`,
`Cheaha State Park`,
`Chewacla State Park`,
`DeSoto State Park`,
`Frank Jackson State Park`,
`Gulf State Park`,
`Joe Wheeler State Park`,
`Lake Guntersville State Park`,
`Lake Lurleen State Park`,
`Lakepoint Resort State Park`,
`Meaher State Park`,
`Monte Sano State Park`,
`Oak Mountain State Park`,
`Rickwood Caverns State Park`,
`Wind Creek State Park`,
`Bladon Springs State Park`,
`Historic Blakeley State Park`,
`Brierfield Ironworks Historical State Park`,
`Chattahoochee State Park`,
`Chickasaw State Park`,
`Florala City Park`,
`Paul M. Grist State Park`,
`Roland Cooper State Park`,
`Tannehill Ironworks Historical State Park`,
`Chugach State Park`,
`Dry Creek State Recreation Site`,
`Lake Louise State Recreation Area`,
`Liberty Falls State Recreation Site`,
`Porcupine Creek State Recreation Site`,
`Squirrel Creek State Recreation Site`,
`Fairbanks area`,
`Birch Lake State Recreation Site`,
`Chena River State Recreation Area`,
`Chena River State Recreation Site`,
`Harding Lake State Recreation Area`,
`Lower Chatanika River State Recreation Area`,
`Salcha River State Recreation Site`,
`Upper Chatanika River State Recreation Site`,
`Delta Junction area`,
`Big Delta State Historical Park`,
`Clearwater State Recreation Site`,
`Delta State Recreation Site`,
`Donnelly Creek State Recreation Site`,
`Fielding Lake State Recreation Site`,
`Quartz Lake State Recreation Area`,
`Tok area`,
`Eagle Trail State Recreation Site`,
`Moon Lake State Recreation Site`,
`Tok River State Recreation Site`,
`Homer area`,
`Anchor River State Recreation Area`,
`Deep Creek State Recreation Area`,
`Diamond Creek State Recreation Area`,
`Stariski State Recreation Site`,
`Kachemak Bay State Park`,
`Kachemak Bay State Wilderness Park`,
`Ninilchik State Recreation Area`,
`Captain Cook State Recreation Area`,
`Stormy Lake at Captain Cook SRA`,
`Clam Gulch State Recreation Area`,
`Crooked Creek State Recreation Site`,
`Johnson Lake State Recreation Area`,
`Kasilof River State Recreation Site`,
`Kenai River Special Management Area`,
`Morgan’s Landing State Recreation Area`,
`Scout Lake State Recreation Site`,
`Seward area`,
`Caines Head State Recreation Area`,
`Driftwood Bay State Marine Park`,
`Lowell Point State Recreation Site`,
`Safety Cove State Marine Park`,
`Sandspit Point State Marine Park`,
`Sunny Cove State Marine Park`,
`Thumb Cove State Marine Park`,
`Afognak Island State Park`,
`Buskin River State Recreation Site`,
`Fort Abercrombie State Historical Park`,
`Pasagshak River State Recreation Site`,
`Shuyak Island State Park`,
`Woody Island State Recreation Site`,
`Big Lake North State Recreation Area`,
`Big Lake South State Recreation Site`,
`Blair Lake State Recreation Site`,
`Denali State Park`,
`Lake Louise State Recreation Area`,
`Nancy Lake State Recreation Area`,
`Nancy Lake State Recreation Site`,
`Finger Lake State Recreation Area`,
`Hatcher Pass East Special Management Area`,
`Independence Mine State Historical Park`,
`Kepler-Bradley Lakes State Recreation Area`,
`King Mountain State Recreation Site`,
`Matanuska Glacier State Recreation Site`,
`Montana Creek State Recreation Site`,
`Rocky Lake State Recreation Site`,
`Summit Lake State Recreation Site`,
`Tokositna River State Recreation Site`,
`Willow Creek State Recreation Area`,
`Bettles Bay State Marine Park`,
`Blueberry Lake State Recreation Site`,
`Boswell Bay Beaches State Marine Park`,
`Canoe Passage State Marine Park`,
`Decision Point State Marine Park`,
`Entry Cove State Marine Park`,
`Granite Bay State Marine Park`,
`Horseshoe Bay State Marine Park`,
`Jack Bay State Marine Park`,
`Kayak Island State Marine Park`,
`Sawmill Bay State Marine Park`,
`Shoup Bay State Marine Park`,
`South Esther Island State Marine Park`,
`Surprise Cove State Marine Park`,
`Surprise Ridge State Marine Park`,
`Worthington Glacier State Recreation Site`,
`Ziegler Cove State Marine Park`,
`Alaska Chilkat Bald Eagle Preserve`,
`Chilkat Islands State Marine Park`,
`Chilkat State Park`,
`Chilkoot Lake State Recreation Site`,
`Mosquito Lake State Recreation Site`,
`Portage Cove State Recreation Site`,
`Sullivan Island State Marine Park`,
`Juneau area`,
`Eagle Beach State Recreation Area`,
`Ernest Gruening State Historical Park`,
`Funter Bay State Marine Park`,
`Juneau Trail System`,
`Oliver Inlet State Marine Park`,
`Point Bridget State Park`,
`Shelter Island State Marine Park`,
`St. James Bay State Marine Park`,
`Taku Harbor State Marine Park`,
`Wickersham State Historic Site`,
`Ketchikan area`,
`Black Sands Beach State Marine Park`,
`Dall Bay State Marine Park`,
`Grindall Island State Marine Park`,
`Refuge Cove State Recreation Site`,
`Settlers Cove State Recreation Site`,
`Totem Bight State Historical Park`,
`Sitka area`,
`Baranof Castle Hill State Historic Site`,
`Big Bear/Baby Bear State Marine Park`,
`Halibut Point State Recreation Site`,
`Magoun Islands State Marine Park`,
`Old Sitka State Historical Park`,
`Sealion Cove State Marine Park`,
`Security Bay State Marine Park`,
`Wrangell/Petersburg area`,
`Beecher Pass State Marine Park`,
`Joe Mace Island State Marine Park`,
`Petroglyph Beach State Historic Site`,
`Thoms Place State Marine Park`,
`Lake Aleknagik State Recreation Site`,
`Wood-Tikchik State Park`,
`Mount Nebo State Park`,
`Ozark Folk Center State Park`,
`Parkin Archeological State Park`,
`Petit Jean State Park`,
`Pinnacle Mountain State Park`,
`Plantation Agriculture Museum`,
`Poison Springs Battleground State Park`,
`Powhatan Historic State Park`,
`Prairie Grove Battlefield State Park`,
`Queen Wilhelmina State Park`,
`South Arkansas Arboretum`,
`Toltec Mounds Archeological State Park`,
`Village Creek State Park`,
`White Oak Lake State Park`,
`Withrow Springs State Park`,
`Woolly Hollow State Park`,
`Above All State Park`,
`Beaver Brook State Park`,
`Becket Hill State Park Reserve`,
`Beckley Furnace Industrial Monument`,
`Bennett's Pond State Park`,
`Bigelow Hollow State Park`,
`Black Rock State Park`,
`Bluff Point State Park`,
`Bolton Notch State Park`,
`Brainard Homestead State Park`,
`Burr Pond State Park`,
`Camp Columbia State Park/State Forest`,
`Campbell Falls State Park Reserve`,
`Chatfield Hollow State Park`,
`Collis P. Huntington State Park`,
`Connecticut Valley Railroad State Park`,
`Dart Island State Park`,
`Day Pond State Park`,
`Dennis Hill State Park`,
`Devil's Hopyard State Park`,
`Dinosaur State Park`,
`Eagle Landing State Park`,
`Farm River State Park`,
`Ferry Landing State Park`,
`Fort Griswold Battlefield State Park`,
`Fort Trumbull State Park`,
`Gardner Lake State Park`,
`Gay City State Park`,
`George Dudley Seymour State Park`,
`George Waldo State Park`,
`Gillette Castle State Park`,
`Haddam Island State Park`,
`Haddam Meadows State Park`,
`Haley Farm State Park`,
`Hammonasset Beach State Park`,
`Harkness Memorial State Park`,
`Haystack Mountain State Park`,
`Higganum Reservoir State Park`,
`Hopemead State Park`,
`Hopeville Pond State Park`,
`Horse Guard State Park`,
`Housatonic Meadows State Park`,
`Humaston Brook State Park`,
`Hurd State Park`,
`Indian Well State Park`,
`John A. Minetto State Park`,
`Kent Falls State Park`,
`Kettletown State Park`,
`Killingly Pond State Park`,
`Lake Waramaug State Park`,
`Lamentation Mountain State Park`,
`Lovers Leap State Park`,
`Macedonia Brook State Park`,
`Machimoodus State Park`,
`Mansfield Hollow State Park`,
`Mashamoquet Brook State Park`,
`Mianus River State Park`,
`Millers Pond State Park`,
`Minnie Island State Park`,
`Mohawk Forest/Mohawk Mountain State Park`,
`Mono Pond State Park Reserve`,
`Mooween State Park`,
`Mount Bushnell State Park`,
`Mount Riga State Park`,
`Mount Tom State Park`,
`Old Furnace State Park`,
`Osbornedale State Park`,
`Penwood State Park`,
`Platt Hill State Park`,
`Pomeroy State Park`,
`Putnam Memorial State Park`,
`Quaddick State Park`,
`Quinebaug Lake State Park`,
`Quinnipiac River State Park`,
`River Highlands State Park`,
`Rocky Glen State Park`,
`Rocky Neck State Park`,
`Ross Pond State Park`,
`Salt Rock State Campground`,
`Satan's Kingdom State Recreation Area`,
`Scantic River State Park`,
`Selden Neck State Park`,
`Seth Low Pierrepont State Park Reserve`,
`Sherwood Island State Park`,
`Silver Sands State Park`,
`Sleeping Giant State Park`,
`Southford Falls State Park`,
`Squantz Pond State Park`,
`Stillwater Pond State Park`,
`Stoddard Hill State Park`,
`Stratton Brook State Park`,
`Sunnybrook State Park`,
`Sunrise State Park`,
`Talcott Mountain State Park`,
`Tri-Mountain State Park`,
`Trout Brook Valley State Park Reserve`,
`Wadsworth Falls State Park`,
`West Rock Ridge State Park`,
`Wharton Brook State Park`,
`Whittemore Glen State Park`,
`Windsor Meadows State Park`,
`Wooster Mountain State Park`,
`Woolly Hollow State Park`,
`Algonquin State Forest`,
`American Legion State Forest`,
`Camp Columbia State Park/State Forest`,
`Centennial Watershed State Forest`,
`Cockaponset State Forest`,
`Enders State Forest`,
`Housatonic State Forest`,
`James L. Goodwin State Forest`,
`Massacoe State Forest`,
`Mattatuck State Forest`,
`Meshomasic State Forest`,
`Mohawk State Forest`,
`Mohegan State Forest`,
`Nassahegon State Forest`,
`Natchaug State Forest`,
`Nathan Hale State Forest`,
`Naugatuck State Forest`,
`Nehantic State Forest`,
`Nepaug State Forest`,
`Nipmuck State Forest`,
`Nye-Holman State Forest`,
`Pachaug State Forest`,
`Paugnut State Forest`,
`Paugussett State Forest`,
`Peoples State Forest`,
`Pootatuck State Forest`,
`Quaddick State Forest`,
`Salmon River State Forest`,
`Shenipsit State Forest`,
`Topsmead State Forest`,
`Tunxis State Forest`,
`Wyantenock State Forest`,
`Connecticut Wildlife Management Areas[edit]`,
`Aldo Leopold Wildlife Management Area`,
`Assekonk Swamp Wildlife Management Area`,
`Babcock Pond Wildlife Management Area`,
`Barber Pond Wildlife Management Area`,
`Barn Island Wildlife Management Area`,
`Bartlett Brook Wildlife Management Area`,
`Bear Hill Wildlife Management Area`,
`Belding Wildlife Management Area`,
`Bishops Swamp Wildlife Management Area`,
`Black Pond Wildlife Management Area`,
`Candlewood Hill Wildlife Management Area`,
`Cedar Swamp Wildlife Management Area`,
`Charles E. Wheeler Wildlife Management Area`,
`Charter Marsh Wildlife Sanctuary`,
`Cromwell Meadows Wildlife Management Area`,
`Durham Meadows Wildlife Management Area`,
`East River Marsh Wildlife Management Area`,
`East Swamp Wildlife Management Area`,
`Eightmile River Wildlife Management Area`,
`Franklin Wildlife Management Area`,
`Goshen Wildlife Management Area`,
`Great Harbor Wildlife Management Area`,
`Higganum Meadows Wildlife Management Area`,
`Housatonic River Wildlife Management Area`,
`King's Island Coop Wildlife Management Area`,
`Kollar Wildlife Management Area`,
`Larson Lot Wildlife Management Area`,
`Little River Fish and Wildlife Area`,
`Lord's Cove Wildlife Management Area`,
`Maromas Coop Wildlife Management Area`,
`Meadow Brook Wildlife Management Area`,
`Menunketesuck Wildlife Management Area`,
`Messerschmidt Wildlife Management Area`,
`Newgate Wildlife Management Area`,
`Nod Brook Wildlife Management Area`,
`Nott Island Wildlife Management Area`,
`Pease Brook Wildlife Management Area`,
`Plum Bank Wildlife Management Area`,
`Quinebaug River Wildlife Management Area`,
`Quinnipiac River Marsh Wildlife Management Area`,
`Ragged Rock Wildlife Management Area`,
`Raymond Brook Marsh Wildlife Management Area`,
`Robbins Swamp Wildlife Management Area`,
`Roger Tory Peterson Wildlife Area`,
`Roraback Wildlife Management Area`,
`Rose Hill Wildlife Management Area`,
`Ross Marsh Wildlife Management Area`,
`Salmon River Cove and Haddam Neck Wildlife Management Area`,
`Sessions Woods Wildlife Management Area`,
`Simsbury Wildlife Management Area`,
`Skiff Mountain Coop Wildlife Management Area`,
`James V. Spignesi Wildlife Management Area`,
`Stanley Works Wildlife Management Area`,
`Suffield Wildlife Management Area`,
`Talbot Wildlife Management Area`,
`Tankerhoosen Wildlife Management Area`,
`Wangunk Meadows Wildlife Management Area`,
`Wopowog Wildlife Management Area`,
`Zemko Pond Wildlife Management Area`,
`Alapocas Run`,
`Auburn Valley`,
`Bellevue`,
`Brandywine Creek`,
`Cape Henlopen`,
`Delaware Seashore`,
`Fenwick Island`,
`First State Heritage`,
`Fort Delaware`,
`Fort DuPont`,
`Fox Point`,
`Holts Landing`,
`Killens Pond`,
`Lums Pond`,
`Trap Pond`,
`White Clay Creek`,
`Addison Blockhouse Historic State Park`,
`Alafia River State Park`,
`Alfred B. Maclay Gardens State Park`,
`Allen David Broussard Catfish Creek Preserve State Park`,
`Amelia Island State Park`,
`Anastasia State Park`,
`Anclote Key Preserve State Park`,
`Avalon State Park`,
`Bahia Honda State Park`,
`Bald Point State Park`,
`The Barnacle Historic State Park`,
`Big Lagoon State Park`,
`Big Shoals State Park`,
`Big Talbot Island State Park`,
`Bill Baggs Cape Florida State Park`,
`Blackwater River State Park`,
`Blue Spring State Park`,
`Bulow Creek State Park`,
`Bulow Plantation Ruins Historic State Park`,
`Caladesi Island State Park`,
`Camp Helen State Park`,
`Cayo Costa State Park`,
`Cedar Key Scrub State Reserve`,
`Cedar Key Museum State Park`,
`Charlotte Harbor Preserve State Park`,
`Collier-Seminole State Park`,
`Colt Creek State Park`,
`Constitution Convention Museum State Park`,
`Crystal River Archaeological State Park`,
`Crystal River Preserve State Park`,
`Curry Hammock State Park`,
`Dade Battlefield Historic State Park`,
`Dagny Johnson Key Largo Hammock Botanical State Park`,
`De Leon Springs State Park`,
`DeSoto Site Historic State Park`,
`Deer Lake State Park`,
`Delnor-Wiggins Pass State Park`,
`Devil's Millhopper Geological State Park`,
`Don Pedro Island State Park`,
`Dr. Von D. Mizell-Eula Johnson State Park`,
`Dudley Farm Historic State Park`,
`Dunns Creek State Park`,
`Econfina River State Park`,
`Eden Gardens State Park`,
`Edward Ball Wakulla Springs State Park`,
`Egmont Key State Park`,
`Estero Bay Preserve State Park`,
`Fakahatchee Strand Preserve State Park`,
`Falling Waters State Park`,
`Fanning Springs State Park`,
`Faver-Dykes State Park`,
`Florida Caverns State Park`,
`Forest Capital Museum State Park`,
`Fort Clinch State Park`,
`Fort Cooper State Park`,
`Fort Foster State Historic Site`,
`Fort George Island Cultural State Park`,
`Fort Mose Historic State Park`,
`Fort Pierce Inlet State Park`,
`Fort Zachary Taylor Historic State Park`,
`Fred Gannon Rocky Bayou State Park`,
`Gainesville-Hawthorne State Trail`,
`Gamble Plantation Historic State Park`,
`Gamble Rogers Memorial State Recreation Area at Flagler Beach`,
`Gasparilla Island State Park`,
`George Crady Bridge Fishing Pier`,
`Gilchrist Blue Springs State Park`,
`Grayton Beach State Park`,
`Henderson Beach State Park`,
`Highlands Hammock State Park`,
`Hillsborough River State Park`,
`Homosassa Springs Wildlife State Park`,
`Honeymoon Island State Park`,
`Hontoon Island State Park`,
`Hugh Taylor Birch State Park`,
`Ichetucknee Springs State Park`,
`Indian Key Historic State Park`,
`John D. MacArthur Beach State Park`,
`John Gorrie Museum State Park`,
`John Pennekamp Coral Reef State Park`,
`Jonathan Dickinson State Park`,
`Kissimmee Prairie Preserve State Park`,
`Koreshan State Historic Site`,
`Lafayette Blue Springs State Park`,
`Lake Griffin State Park`,
`Lake Jackson Mounds Archaeological State Park`,
`Lake June in Winter Scrub State Park`,
`Lake Kissimmee State Park`,
`Lake Louisa State Park`,
`Lake Manatee State Park`,
`Lake Talquin State Park`,
`Letchworth-Love Mounds Archaeological State Park`,
`Lignumvitae Key Botanical State Park`,
`Little Manatee River State Park`,
`Little Talbot Island State Park`,
`Long Key State Park`,
`Lovers Key State Park`,
`Lower Wekiva River Preserve State Park`,
`Madira Bickel Mound State Archaeological Site`,
`Madison Blue Spring State Park`,
`Manatee Springs State Park`,
`Marjorie Kinnan Rawlings Historic State Park`,
`Mike Roess Gold Head Branch State Park`,
`Mound Key Archaeological State Park`,
`Myakka River State Park`,
`Natural Bridge Battlefield Historic State Park`,
`North Peninsula State Park`,
`Okeechobee Battlefield State Park`,
`O'Leno State Park`,
`Ochlockonee River State Park`,
`Oleta River State Park`,
`Olustee Battlefield Historic State Park`,
`Orman House Historic State Park`,
`Oscar Scherer State Park`,
`Paynes Creek Historic State Park`,
`Paynes Prairie Preserve State Park`,
`Perdido Key State Park`,
`Price's Scrub State Park`,
`Ponce de Leon Springs State Park`,
`Pumpkin Hill Creek Preserve State Park`,
`Rainbow Springs State Park`,
`Ravine Gardens State Park`,
`River Rise Preserve State Park`,
`Rock Springs Run State Reserve`,
`San Felasco Hammock Preserve State Park`,
`San Marcos de Apalache Historic State Park`,
`San Pedro Underwater Archaeological Preserve State Park`,
`Savannas Preserve State Park`,
`Seabranch Preserve State Park`,
`Sebastian Inlet State Park`,
`Silver Springs State Park`,
`Skyway Fishing Pier State Park`,
`St. Andrews State Park`,
`St. George Island State Park`,
`St. Lucie Inlet Preserve State Park`,
`St. Marks River Preserve State Park`,
`St. Sebastian River Preserve State Park`,
`Stephen Foster Folk Culture Center State Park`,
`Stump Pass Beach State Park`,
`Suwannee River State Park`,
`T.H. Stone Memorial St. Joseph Peninsula State Park`,
`Tarkiln Bayou Preserve State Park`,
`Terra Ceia Preserve State Park`,
`Three Rivers State Park`,
`Tomoka State Park`,
`Topsail Hill Preserve State Park`,
`Torreya State Park`,
`Troy Spring State Park`,
`Waccasassa Bay Preserve State Park`,
`Washington Oaks Gardens State Park`,
`Weeki Wachee Springs`,
`Wekiwa Springs State Park`,
`Werner-Boyce Salt Springs State Park`,
`Wes Skiles Peacock Springs State Park`,
`Windley Key Fossil Reef Geological State Park`,
`Ybor City Museum State Park`,
`Yellow Bluff Fort Historic State Park`,
`Yellow River Marsh Preserve State Park`,
`Yulee Sugar Mill Ruins Historic State Park`,
`Ashton to Tetonia Trail`,
`Bear Lake State Park`,
`Bruneau Dunes State Park`,
`Castle Rocks State Park`,
`City of Rocks National Reserve`,
`Coeur d'Alene Parkway State Park`,
`Dworshak State Park`,
`Eagle Island State Park`,
`Farragut State Park`,
`Harriman State Park`,
`Hells Gate State Park`,
`Henrys Lake State Park`,
`Heyburn State Park`,
`Lake Cascade State Park`,
`Lake Walcott State Park`,
`Land of the Yankee Fork State Park`,
`Lucky Peak State Park`,
`Massacre Rocks State Park`,
`McCroskey State Park`,
`Old Mission State Park`,
`Ponderosa State Park`,
`Priest Lake State Park`,
`Round Lake State Park`,
`Thousand Springs State Park`,
`Three Island Crossing State Park`,
`Trail of the Coeur d'Alenes`,
`Winchester Lake State Park`,
`Adeline Jay Geo-Karis Illinois Beach State Park`,
`Anderson Lake State Fish & Wildlife Area`,
`Apple River Canyon State Park`,
`Argyle Lake State Park`,
`Baldwin Lake State Fish & Wildlife Area`,
`Banner Marsh State Fish and Wildlife Area`,
`Bartlett Woods Nature Preserve`,
`Beall Woods State Park`,
`Beaver Dam State Park`,
`Big River State Forest`,
`Bohm Woods Nature Preserve[3]`,
`Buffalo Rock State Park & Effigy Tumuli`,
`Cache River State Natural Area`,
`Cape Bend State Fish and Wildlife Area[4]`,
`Carlyle Lake State Fish and Wildlife Area`,
`Castle Rock State Park`,
`Cave-in-Rock State Park`,
`Chain O'Lakes State Park`,
`Channahon State Park`,
`Clinton Lake State Recreation Area`,
`Coffeen Lake State Fish and Wildlife Area`,
`Crawford County State Fish and Wildlife Area`,
`Delabar State Park`,
`Des Plaines Fish and Wildlife Area`,
`Dixon Springs State Park`,
`Donnelley/Depue State Park`,
`Double T State Fish and Wildlife Area`,
`Eagle Creek State Recreation Area`,
`Edward R. Madigan State Fish and Wildlife Area`,
`Eldon Hazlet State Recreation Area`,
`Ferne Clyffe State Park`,
`Fort Massac State Park`,
`Fox Ridge State Park`,
`Frank Holten State Recreation Area`,
`Franklin Creek State Natural Area`,
`Fults Hill Prairie State Natural Area`,
`Gebhard Woods State Park`,
`Giant City State Park`,
`Golconda Marina State Recreation Area`,
`Goose Lake Prairie State Natural Area`,
`Green River State Wildlife Area`,
`Hamilton County State Fish and Wildlife Area`,
`Harry "Babe" Woodyard State Natural Area`,
`Hazel & Bill Rutherford Wildlife Prairie State Park`,
`Heidecke Lake State Fish & Wildlife Area`,
`Hennepin Canal Parkway State Park`,
`Hidden Springs State Forest`,
`Horseshoe Lake State Fish & Wildlife Area`,
`Horseshoe Lake State Park`,
`Illini State Park`,
`Illinois Caverns State Natural Area`,
`Iroquois County State Wildlife Area`,
`James "Pate" Philip State Park`,
`Jim Edgar Panther Creek State Fish and Wildlife Area`,
`Johnson-Sauk Trail State Park`,
`Jubilee College State Park`,
`Kankakee River State Park`,
`Kaskaskia River State Fish & Wildlife Area`,
`Kickapoo State Recreation Area`,
`Kinkaid Lake State Fish and Wildlife Area`,
`Kishwaukee River State Fish and Wildlife Area`,
`Lake Le-Aqua-Na State Park`,
`Lake Murphysboro State Park`,
`LaSalle Lake State Fish & Wildlife Area`,
`Lewis and Clark State Historic Site`,
`Lincoln Trail Homestead State Memorial`,
`Lincoln Trail State Park`,
`Lowden State Park`,
`Brown County State Park`,
`Chain O' Lakes State Park`,
`Charlestown State Park`,
`Clifty Falls State Park`,
`Falls of the Ohio State Park`,
`Fort Harrison State Park`,
`Harmonie State Park`,
`Indiana Dunes State Park`,
`Lincoln State Park`,
`McCormick's Creek State Park`,
`Mounds State Park`,
`O'Bannon Woods State Park`,
`Ambrose A. Call State Park`,
`Backbone State Park`,
`Badger Creek State Recreation Area`,
`Banner Lakes at Summerset State Park`,
`Beed's Lake State Park`,
`Bellevue State Park`,
`Big Creek State Park`,
`Black Hawk State Park`,
`Brushy Creek State Recreation Area`,
`Cedar Rock State Park`,
`Clear Lake State Park`,
`Dolliver Memorial State Park`,
`Elinor Bedell State Park`,
`Elk Rock State Park`,
`Emerson Bay State Recreation Area`,
`Fairport State Recreation Area`,
`Fort Atkinson State Preserve`,
`Fort Defiance State Park`,
`Geode State Park`,
`George Wyth Memorial State Park`,
`Green Valley State Park`,
`Gull Point State Park`,
`Honey Creek State Park`,
`Honey Creek Resort State Park`,
`Lacey-Keosauqua State Park`,
`Lake Ahquabi State Park`,
`Lake Anita State Park`,
`Lake Darling State Park`,
`Lake Keomah State Park`,
`Lake Macbride State Park`,
`Lake Manawa State Park`,
`Lake of Three Fires State Park`,
`Lake Wapello State Park`,
`Ledges State Park`,
`Lewis and Clark State Park`,
`Lower Gar State Recreation Area`,
`Maquoketa Caves State Park`,
`Marble Beach State Recreation Area`,
`McIntosh Woods State Park`,
`Mines of Spain State Recreation Area and E. B. Lyons Nature Center`,
`Mini-Wakan State Park`,
`Nine Eagles State Park`,
`Okamanpedan State Park`,
`Palisades-Kepler State Park`,
`Pikes Peak State Park`,
`Pikes Point State Park`,
`Pilot Knob State Park`,
`Pine Lake State Park`,
`Pleasant Creek State Recreation Area`,
`Prairie Rose State Park`,
`Preparation Canyon State Park`,
`Red Haw State Park`,
`Rice Lake State Park`,
`Rock Creek State Park`,
`Springbrook State Park`,
`Stone State Park`,
`Templar State Recreation Area`,
`Trapper's Bay State Park`,
`Twin Lakes State Park`,
`Union Grove State Park`,
`Viking Lake State Park`,
`Volga River State Recreation Area`,
`Walnut Woods State Park`,
`Wapsipinicon State Park`,
`Waubonsie State Park`,
`Wildcat Den State Park`,
`Wilson Island State Recreation Area`,
`Bobwhite State Park`,
`Cold Springs State Park`,
`Crystal Lake State Park`,
`Eagle Lake State Park`,
`Echo Valley State Park`,
`Frank A. Gotch State Park`,
`Heery Woods State Park`,
`Kearny State Park`,
`Lake Cornelia State Park`,
`Lake Icaria State Park`,
`Margo Frankel State Park`,
`Mill Creek State Park`,
`Oak Grove State Park`,
`Oakland Mills State Park`,
`Pammel State Park`,
`Sharon Bluffs State Park`,
`Spring Lake State Park`,
`Swan Lake State Park`,
`Three Mile Lake State Park`,
`Cedar Bluff State Park`,
`Cheney State Park`,
`Clinton State Park`,
`Crawford State Park`,
`Cross Timbers State Park`,
`Eisenhower State Park`,
`El Dorado State Park`,
`Elk City State Park`,
`Fall River State Park`,
`Waconda Lake (Glen Elder Reservoir)`,
`Hillsdale State Park`,
`Kaw River State Park`,
`Kanopolis State Park`,
`Lovewell State Park`,
`Meade State Park`,
`Milford Lake`,
`Mushroom Rock State Park`,
`Perry State Park`,
`Pomona State Park`,
`Prairie Dog State Park`,
`Prairie Spirit Trail State Park`,
`Sand Hills State Park`,
`Lake Scott State Park`,
`Little Jerusalem Badlands State Park`,
`Tuttle Creek Lake`,
`Webster State Park`,
`Wilson State Park`,
`Columbus-Belmont State Park`,
`Dawkins Line Rail Trail`,
`E. P. "Tom" Sawyer State Park`,
`Fishtrap Lake State Park`,
`Fort Boonesborough State Park`,
`General Burnside State Park`,
`Grayson Lake State Park`,
`Green River Lake State Park`,
`John James Audubon State Park`,
`Kincaid Lake State Park`,
`Kingdom Come State Park`,
`Lake Malone State Park`,
`Levi Jackson Wilderness Road State Park`,
`Lincoln Homestead State Park`,
`Mineral Mound State Park`,
`My Old Kentucky Home State Park`,
`Nolin Lake State Park`,
`Old Fort Harrod State Park`,
`Paintsville Lake State Park`,
`Pine Mountain State Scenic Trail`,
`Taylorsville Lake State Park`,
`Yatesville Lake State Park`,
`Carr Creek State Park`,
`Barren River Lake State Resort Park`,
`Blue Licks Battlefield State Park`,
`Breaks Interstate Park`,
`Buckhorn Lake State Resort Park`,
`Carter Caves State Resort Park`,
`Cumberland Falls State Resort Park`,
`Dale Hollow Lake State Park`,
`General Butler State Resort Park`,
`Greenbo Lake State Resort Park`,
`Jenny Wiley State Resort Park`,
`Kenlake State Resort Park`,
`Kentucky Dam Village State Resort Park`,
`Lake Barkley State Resort Park`,
`Butler-Turpin State Historic House`,
`Dr. Thomas Walker State Historic Site`,
`Isaac Shelby Cemetery State Historic Site`,
`Jefferson Davis State Historic Site`,
`Old Mulkey Meetinghouse State Historic Site`,
`Perryville Battlefield State Historic Site`,
`Waveland State Historic Site`,
`White Hall State Historic Site`,
`Wickliffe Mounds State Historic Site`,
`William Whitley House State Historic Site`,
`Bayou Segnette State Park`,
`Bogue Chitto State Park`,
`Chemin-A-Haut State Park`,
`Chicot State Park`,
`Cypremort Point State Park`,
`Fairview-Riverside State Park`,
`Fontainebleau State Park`,
`Grand Isle State Park`,
`Jimmie Davis State Park`,
`Lake Bistineau State Park`,
`Lake Bruin State Park`,
`Lake Claiborne State Park`,
`Lake D'Arbonne State Park`,
`Lake Fausse Pointe State Park`,
`North Toledo Bend State Park`,
`Palmetto Island State Park`,
`Poverty Point Reservoir State Park`,
`St. Bernard State Park`,
`Sam Houston Jones State Park`,
`South Toledo Bend State Park`,
`Tickfaw State Park`,
`Allagash Wilderness Waterway`,
`Androscoggin Riverlands`,
`Aroostook State Park`,
`Baxter State Park`,
`Birch Point State Park`,
`Bradbury Mountain State Park`,
`Camden Hills State Park`,
`Cobscook Bay State Park`,
`Crescent Beach State Park`,
`Damariscotta Lake State Park`,
`Ferry Beach State Park`,
`Fort Point State Park`,
`Grafton Notch State Park`,
`Holbrook Island Sanctuary State Park`,
`Lake St. George State Park`,
`Lamoine State Park`,
`Lily Bay State Park`,
`Mackworth Island`,
`Moose Point State Park`,
`Mount Blue State Park`,
`Mount Kineo State Park`,
`Owls Head Light State Park`,
`Peacock Beach State Park`,
`Peaks-Kenny State Park`,
`Penobscot River Corridor`,
`Popham Beach State Park`,
`Quoddy Head State Park`,
`Range Ponds State Park`,
`Rangeley Lake State Park`,
`Reid State Park`,
`Roque Bluffs State Park`,
`Sebago Lake State Park`,
`Shackford Head State Park`,
`Swan Lake State Park`,
`Two Lights State Park`,
`Vaughan Woods State Park`,
`Warren Island State Park`,
`Wolfe's Neck Woods State Park`,
`Bible Point`,
`Colburn House State Historic Site`,
`Colonial Pemaquid State Historic Site`,
`Eagle Island State Historic Site`,
`Fort Baldwin State Historic Site`,
`Fort Edgecomb State Historic Site`,
`Fort Halifax State Historic Site`,
`Fort Kent State Historic Site`,
`Fort Knox State Historic Site`,
`Fort McClary State Historic Site`,
`Fort O'Brien State Historic Site`,
`Fort Popham State Historic Site`,
`Fort Pownall`,
`John Paul Jones State Historic Site`,
`Katahdin Iron Works`,
`Storer Garrison State Historic Site`,
`Whaleback Shell Midden`,
`Assateague State Park`,
`Big Run State Park`,
`Bill Burton Fishing Pier State Park`,
`Calvert Cliffs State Park`,
`Casselman River Bridge State Park`,
`Chapel Point State Park`,
`Chapman State Park`,
`Cunningham Falls State Park`,
`Dans Mountain State Park`,
`Deep Creek Lake State Park`,
`Elk Neck State Park`,
`Fort Frederick State Park`,
`Fort Tonoloway State Park`,
`Franklin Point State Park`,
`Gambrill State Park`,
`Gathland State Park`,
`Greenbrier State Park`,
`Greenwell State Park`,
`Gunpowder Falls State Park`,
`Hallowing Point State Park`,
`Harriet Tubman Underground Railroad State Park`,
`Hart-Miller Island State Park`,
`Herrington Manor State Park`,
`Janes Island State Park`,
`Love Point State Park`,
`Martinak State Park`,
`Matapeake State Park`,
`Matthew Henson State Park`,
`New Germany State Park`,
`Newtowne Neck State Park`,
`North Point State Park`,
`Palmer State Park`,
`Patapsco Valley State Park`,
`Patuxent River State Park`,
`Pocomoke River State Park`,
`Point Lookout State Park`,
`Rocks State Park`,
`Rocky Gap State Park`,
`Rosaryville State Park`,
`Sandy Point State Park`,
`Sang Run State Park`,
`Seneca Creek State Park`,
`Smallwood State Park`,
`South Mountain State Park`,
`St. Clement's Island State Park`,
`St. Mary's River State Park`,
`Susquehanna State Park`,
`Swallow Falls State Park`,
`Tuckahoe State Park`,
`Washington Monument State Park`,
`Wills Mountain State Park`,
`Wolf Den Run State Park`,
`Wye Oak State Park`,
`Alewife Brook Reservation`,
`Ames Nowell State Park`,
`Ashland State Park`,
`Bash Bish Falls State Park`,
`Beartown State Forest`,
`Beaver Brook Reservation`,
`Belle Isle Marsh Reservation`,
`Blackstone River and Canal Heritage State Park`,
`Blue Hills Reservation`,
`Borderland State Park`,
`Boston Harbor Islands State Park`,
`Bradley Palmer State Park`,
`Breakheart Reservation`,
`Brimfield State Forest`,
`Bristol Blake State Reservation`,
`Brook Farm Historic Site`,
`C. M. Gardner State Park`,
`Callahan State Park`,
`Camp Nihan Environmental Education Camp`,
`Castle Island`,
`Charles River Reservation`,
`Chester-Blandford State Forest`,
`Chestnut Hill Reservation`,
`Chicopee Memorial State Park`,
`Clarksburg State Park`,
`Cochituate State Park`,
`Connecticut River Greenway State Park`,
`Constitution Beach`,
`Cutler Park Reservation`,
`D.A.R. State Forest`,
`Demarest Lloyd State Park`,
`Dighton Rock State Park`,
`Dorchester Shores Reservation`,
`Douglas State Forest`,
`Dunn State Park`,
`Ellisville Harbor State Park`,
`Elm Bank Reservation`,
`Erving State Forest`,
`F. Gilbert Hills State Forest`,
`Fall River Heritage State Park`,
`Federated Women's Club State Forest`,
`Fort Phoenix State Reservation`,
`Fort Revere Park`,
`Francis D. Martini Memorial Shell Park and Moynihan Recreation Area`,
`Freetown-Fall River State Forest`,
`Gardner Heritage State Park`,
`Georgetown-Rowley State Forest`,
`Granville State Forest`,
`Great Brook Farm State Park`,
`Greycourt State Park`,
`Halibut Point State Park`,
`Hammond Pond Reservation`,
`Hampton Ponds State Park`,
`Harold Parker State Forest`,
`Hemlock Gorge Reservation`,
`Holyoke Heritage State Park`,
`Hopkinton State Park`,
`Horseneck Beach State Reservation`,
`Jug End State Reservation and Wildlife Management Area`,
`Kenneth Dubuque Memorial State Forest`,
`Lake Dennison Recreation Area`,
`Lake Lorraine State Park`,
`Lake Wyola State Park`,
`Lawrence Heritage State Park`,
`Leominster State Forest`,
`Lowell-Dracut-Tyngsboro State Forest`,
`Lowell Heritage State Park`,
`Lynn Heritage State Park`,
`Lynn Shore Reservation`,
`Manuel F. Correllus State Forest`,
`Massasoit State Park`,
`Maudslay State Park`,
`Middlesex Fells Reservation`,
`Mohawk Trail State Forest`,
`Monroe State Forest`,
`Moore State Park`,
`Mount Everett State Reservation`,
`Mount Grace State Forest`,
`Mount Greylock State Reservation`,
`Mount Holyoke Range State Park`,
`Mount Sugarloaf State Reservation`,
`Mount Tom State Reservation`,
`Mount Washington State Forest`,
`Myles Standish Monument State Reservation`,
`Myles Standish State Forest`,
`Mystic River Reservation`,
`Nahant Beach Reservation`,
`Nantasket Beach Reservation`,
`Nasketucket Bay State Reservation`,
`Natural Bridge State Park`,
`Neponset River Reservation`,
`Nickerson State Park`,
`October Mountain State Forest`,
`Otter River State Forest`,
`Pearl Hill State Park`,
`Pilgrim Memorial State Park`,
`Pittsfield State Forest`,
`Pope John Paul II Park Reservation`,
`Purgatory Chasm State Reservation`,
`Quabbin Reservoir`,
`Quincy Quarries Reservation`,
`Quincy Shores Reservation`,
`Quinsigamond State Park`,
`Revere Beach Reservation`,
`Robinson State Park`,
`Roxbury Heritage State Park`,
`Rumney Marsh Reservation`,
`Rutland State Park`,
`Salisbury Beach State Reservation`,
`Sandisfield State Forest`,
`Sandy Point State Reservation`,
`Savoy Mountain State Forest`,
`Scusset Beach State Reservation`,
`Shawme-Crowell State Forest`,
`J.A. Skinner State Park`,
`South Cape Beach State Park`,
`Southwest Corridor Park`,
`Spencer State Forest`,
`Squantum Point Park`,
`Stony Brook Reservation`,
`Streeter Point Recreation Area`,
`Sudbury Reservoir`,
`Tolland State Forest`,
`Upper Charles River Reservation`,
`Upton State Forest`,
`Wachusett Mountain State Reservation`,
`Wachusett Reservoir`,
`Wahconah Falls State Park`,
`Walden Pond State Reservation`,
`Waquoit Bay National Estuarine Research Reserve`,
`Ware River Watershed Area`,
`Watson Pond State Park`,
`Webb Memorial State Park`,
`Wells State Park`,
`Wendell State Forest`,
`Western Gateway Heritage State Park`,
`Weymouth Back River Reservation`,
`Whitehall State Park`,
`Willard Brook State Forest`,
`Willowdale State Forest`,
`Wilson Mountain Reservation`,
`Windsor State Forest`,
`Winthrop Shore Reservation`,
`Wompatuck State Park`,
`Des Moines River`,
`Maquoketa River, Backbone Lake`,
`Badger Creek Lake`,
`Banner Lakes`,
`Beed's Lake`,
`Mississippi River`,
`Big Creek Lake`,
`Black Hawk Lake`,
`Des Moines River, Brushy Creek Reservoir`,
`Wapsipinicon River`,
`Clear Lake`,
`Des Moines River`,
`East Okoboji Lake`,
`Lake Red Rock`,
`West Okoboji Lake`,
`Mississippi River`,
`None`,
`None`,
`Skunk River, Lake Geode`,
`Cedar River and several lakes`,
`Green Valley Lake`,
`West Okoboji Lake`,
`Rathbun Lake`,
`Rathbun Lake`,
`Des Moines River`,
`Lake Ahquabi`,
`Lake Anita`,
`Lake Darling`,
`Lake Keomah`,
`Lake Macbride, Coralville Lake`,
`Lake Manawa`,
`Lake of Three Fires`,
`Lake Wapello`,
`Des Moines River, Pea's Creek`,
`Blue Lake`,
`Lower Gar Lake`,
`Raccoon Creek`,
`Spirit Lake`,
`Clear Lake`,
`Mississippi River`,
`Spirit Lake`,
`Nine Eagles Lake`,
`Okamanpeedan Lake`,
`Cedar River`,
`Mississippi River`,
`West Okoboji Lake`,
`Pilot Knob Lake, Dead Man's Lake`,
`Iowa River, Upper and Lower Pine Lakes`,
`Pleasant Creek Lake`,
`Prairie Rose Lake`,
`None`,
`Red Haw Lake`,
`Rice Lake`,
`Rock Creek Lake`,
`Middle Raccoon River`,
`Big Sioux River`,
`Spirit Lake`,
`Silver Lake`,
`North Twin Lakes`,
`Union Grove Lake`,
`Viking Lake`,
`Volga River, Frog Hollow Lake`,
`Raccoon River`,
`Wapsipinicon River, Dutch Creek`,
`Lake Virginia`,
`Pine Creek`,
`Woolly Hollow State Park`,
`Woolly Hollow State Park`,
`Woolly Hollow State Park`,
`Algonac State Park`,
`Aloha State Park`,
`Baraga State Park`,
`Bay City State Park`,
`Belle Isle Park`,
`Bewabic State Park`,
`Brimley State Park`,
`Burt Lake State Park`,
`Cambridge Junction Historic State Park`,
`Cheboygan State Park`,
`Clear Lake State Park`,
`Coldwater Lake State Park`,
`Colonial Michilimackinac Historic State Park`,
`Craig Lake State Park`,
`Dodge #4 State Park`,
`Duck Lake State Park`,
`Fayette Historic State Park`,
`Fisherman's Island State Park`,
`Fort Wilkins Historic State Park`,
`Grand Haven State Park`,
`Grand Mere State Park`,
`Harrisville State Park`,
`Hartwick Pines State Park`,
`Hayes State Park`,
`Historic Mill Creek Discovery Park`,
`Hoeft State Park`,
`Hoffmaster State Park`,
`Holland State Park`,
`Indian Lake State Park`,
`Interlochen State Park`,
`Keith J. Charters Traverse City State Park`,
`Lake Gogebic State Park`,
`Lakeport State Park`,
`Laughing Whitefish Falls State Park`,
`Leelanau State Park`,
`Ludington State Park`,
`Mackinac Island and Fort Mackinac Historic Park`,
`Maybury State Park`,
`McLain State Park`,
`Mears State Park`,
`Meridian-Baseline State Park`,
`Mitchell State Park`,
`Muskallonge Lake State Park`,
`Muskegon State Park`,
`Negwegon State Park`,
`Newaygo State Park`,
`North Higgins Lake State Park`,
`Old Mission State Park[8]`,
`Onaway State Park`,
`Orchard Beach State Park`,
`Otsego Lake State Park`,
`Palms Book State Park`,
`Petoskey State Park`,
`Porcupine Mountains Wilderness State Park`,
`Port Crescent State Park`,
`Sanilac Petroglyphs Historic State Park`,
`Saugatuck Dunes State Park`,
`Seven Lakes State Park`,
`Silver Lake State Park`,
`Sleeper State Park`,
`Sleepy Hollow State Park`,
`South Higgins Lake State Park`,
`Sterling State Park`,
`Straits State Park`,
`Sturgeon Point State Park`,
`Tahquamenon Falls State Park`,
`Tawas Point State Park`,
`Thompson's Harbor State Park`,
`Twin Lakes State Park`,
`Van Buren State Park`,
`Van Riper State Park`,
`Warren Dunes State Park`,
`Warren Woods State Park`,
`Watkins Lake State Park and County Preserve`,
`Wells State Park`,
`Wilderness State Park`,
`William G. Milliken State Park and Harbor`,
`Wilson State Park`,
`Young State Park`,
`Hart-Montague Trail State Park`,
`Kal-Haven Trail`,
`Lakelands Trail State Park`,
`Van Buren Trail State Park`,
`White Pine Trail State Park`,
`Bald Mountain State Recreation Area`,
`Bass River State Recreation Area`,
`Brighton State Recreation Area`,
`Fort Custer State Recreation Area`,
`Highland State Recreation Area`,
`Holly State Recreation Area`,
`Ionia State Recreation Area`,
`Island Lake State Recreation Area`,
`Lake Hudson State Recreation Area`,
`Lime Island State Recreation Area`,
`Menominee River State Recreation Area`,
`Metamora-Hadley State Recreation Area`,
`Ortonville State Recreation Area`,
`Pinckney State Recreation Area`,
`Pontiac Lake State Recreation Area`,
`Proud Lake State Recreation Area`,
`Rifle River State Recreation Area`,
`Rockport State Recreation Area`,
`Tippy Dam State Recreation Area`,
`Waterloo State Recreation Area`,
`W.C. Wetzel State Recreation Area`,
`Yankee Springs State Recreation Area`,
`Au Sable State Forest`,
`Copper Country State Forest`,
`Escanaba River State Forest`,
`Lake Superior State Forest`,
`Mackinaw State Forest`,
`Pere Marquette State Forest`,
`Agate Falls Scenic Site`,
`Bond Falls Scenic Site`,
`DNR Pocket Park`,
`Father Marquette National Memorial`,
`Ralph A. MacMullan Conference Center`,
`Wagner Falls Scenic Site`,
`Afton State Park`,
`Banning State Park`,
`Bear Head Lake State Park`,
`Beaver Creek Valley State Park`,
`Big Bog State Recreation Area`,
`Big Stone Lake State Park`,
`Blue Mounds State Park`,
`Buffalo River State Park`,
`Camden State Park`,
`Carley State Park`,
`Cascade River State Park`,
`Charles A. Lindbergh State Park`,
`Crow Wing State Park`,
`Cuyuna Country State Recreation Area`,
`Father Hennepin State Park`,
`Flandrau State Park`,
`Forestville/Mystery Cave State Park`,
`Fort Ridgely State Park`,
`Fort Snelling State Park`,
`Franz Jevne State Park`,
`Frontenac State Park`,
`Garden Island State Recreation Area`,
`George H. Crosby Manitou State Park`,
`Glacial Lakes State Park`,
`Glendalough State Park`,
`Gooseberry Falls State Park`,
`Grand Portage State Park`,
`Great River Bluffs State Park`,
`Greenleaf Lake State Recreation Area`,
`Hayes Lake State Park`,
`Hill-Annex Mine State Park`,
`Interstate State Park`,
`Iron Range Off-Highway Vehicle State Recreation Area`,
`Itasca State Park`,
`Jay Cooke State Park`,
`John A. Latsch State Park`,
`Judge C. R. Magney State Park`,
`Kilen Woods State Park`,
`La Salle Lake State Recreation Area`,
`Lac qui Parle State Park`,
`Lake Bemidji State Park`,
`Lake Bronson State Park`,
`Lake Carlos State Park`,
`Lake Louise State Park`,
`Lake Maria State Park`,
`Lake Shetek State Park`,
`Lake Vermilion State Park`,
`Maplewood State Park`,
`McCarthy Beach State Park`,
`Mille Lacs Kathio State Park`,
`Minneopa State Park`,
`Minnesota Valley State Recreation Area`,
`Monson Lake State Park`,
`Moose Lake State Park`,
`Myre-Big Island State Park`,
`Nerstrand-Big Woods State Park`,
`Old Mill State Park`,
`Red River State Recreation Area`,
`Rice Lake State Park`,
`St. Croix Islands State Recreation Area`,
`St. Croix State Park`,
`Sakatah Lake State Park`,
`Savanna Portage State Park`,
`Scenic State Park`,
`Schoolcraft State Park`,
`Sibley State Park`,
`Soudan Underground Mine State Park`,
`Split Rock Creek State Park`,
`Split Rock Lighthouse State Park`,
`Temperance River State Park`,
`Tettegouche State Park`,
`Upper Sioux Agency State Park`,
`Whitewater State Park`,
`Wild River State Park`,
`William O'Brien State Park`,
`Zippel Bay State Park`,
`Caribou Falls State Wayside`,
`Devils Track Falls State Wayside`,
`Flood Bay State Wayside`,
`Inspiration Peak State Wayside`,
`Joseph R. Brown State Wayside`,
`Kadunce River State Wayside`,
`Ray Berglund State Wayside`,
`St. Croix Boom Site State Wayside`,
`Sam Brown Memorial State Wayside`,
`Arrowhead State Trail`,
`Blazing Star State Trail`,
`Blufflands State Trail: Harmony-Preston Valley Segment`,
`Blufflands State Trail: Root River Segment`,
`Casey Jones State Trail`,
`Central Lakes State Trail`,
`Cuyuna Lakes State Trail`,
`Douglas State Trail`,
`Gateway State Trail`,
`Gitchi-Gami State Trail`,
`Glacial Lakes State Trail`,
`Goodhue Pioneer State Trail`,
`Great River Ridge State Trail`,
`Heartland State Trail`,
`Luce Line State Trail`,
`Mill Towns State Trail`,
`Minnesota Valley State Trail`,
`North Shore State Trail`,
`Paul Bunyan State Trail`,
`Sakatah Singing Hills State Trail`,
`Shooting Star State Trail`,
`Taconite State Trail`,
`Willard Munger State Trail`,
`Buccaneer State Park`,
`Clark Creek Natural Area`,
`Clarkco State Park`,
`Florewood State Park`,
`George P. Cossar State Park`,
`Golden Memorial State Park`,
`Great River Road State Park`,
`Holmes County State Park`,
`Hugh White State Park`,
`John W. Kyle State Park`,
`J. P. Coleman State Park`,
`Lake Lincoln State Park`,
`Lake Lowndes State Park`,
`LeFleur's Bluff State Park`,
`Legion State Park`,
`Leroy Percy State Park`,
`Natchez State Park`,
`Paul B. Johnson State Park`,
`Percy Quin State Park`,
`Roosevelt State Park`,
`Shepard State Park`,
`Tishomingo State Park`,
`Tombigbee State Park`,
`Trace State Park`,
`Wall Doxey State Park`,
`Babler State Park`,
`Sam A. Baker State Park`,
`Bennett Spring State Park`,
`Big Lake State Park`,
`Big Oak Tree State Park`,
`Big Sugar Creek State Park`,
`Bryant Creek State Park`,
`Castlewood State Park`,
`Crowder State Park`,
`Cuivre River State Park`,
`Current River State Park`,
`Don Robinson State Park`,
`Echo Bluff State Park`,
`Elephant Rocks State Park`,
`Eleven Point State Park`,
`Finger Lakes State Park`,
`Graham Cave State Park`,
`Grand Gulf State Park`,
`Ha Ha Tonka State Park`,
`Harry S Truman State Park`,
`Hawn State Park`,
`Jay Nixon State Park`,
`Johnson's Shut-Ins State Park`,
`Jones-Confluence Point State Park`,
`Katy Trail State Park`,
`Knob Noster State Park`,
`Lake of the Ozarks State Park`,
`Lake Wappapello State Park`,
`Lewis and Clark State Park`,
`Long Branch State Park`,
`Mark Twain State Park`,
`Meramec State Park`,
`Montauk State Park`,
`Morris State Park`,
`Onondaga Cave State Park`,
`Ozark Mountain State Park`,
`Pershing State Park`,
`Pomme de Terre State Park`,
`Prairie State Park`,
`Roaring River State Park`,
`Robertsville State Park`,
`Rock Bridge Memorial State Park`,
`Rock Island Trail State Park`,
`Roger Pryor Pioneer Backcountry`,
`Route 66 State Park`,
`St. Francois State Park`,
`St. Joe State Park`,
`Stockton State Park`,
`Table Rock State Park`,
`Taum Sauk Mountain State Park`,
`Thousand Hills State Park`,
`Trail of Tears State Park`,
`Van Meter State Park`,
`Wakonda State Park`,
`Wallace State Park`,
`Washington State Park`,
`Watkins Woolen Mill State Park`,
`Weston Bend State Park`,
`Arrow Rock State Historic Site`,
`Battle of Athens State Historic Site`,
`Battle of Carthage State Historic Site`,
`Battle of Island Mound State Historic Site`,
`Battle of Lexington State Historic Site`,
`Battle of Pilot Knob State Historic Site`,
`Thomas Hart Benton Home and Studio State Historic Site`,
`Bollinger Mill State Historic Site`,
`Nathan Boone Homestead State Historic Site`,
`Boone's Lick State Historic Site`,
`Bothwell Lodge State Historic Site`,
`Clark's Hill/Norton State Historic Site`,
`Confederate Memorial State Historic Site`,
`Deutschheim State Historic Site`,
`Dillard Mill State Historic Site`,
`Gov. Daniel Dunklin's Grave State Historic Site`,
`Felix Vallé House State Historic Site`,
`First Missouri State Capitol State Historic Site`,
`Gen. John J. Pershing Boyhood Home State Historic Site`,
`Harry S Truman Birthplace State Historic Site`,
`Hunter-Dawson State Historic Site`,
`Iliniwek Village State Historic Site`,
`Jefferson Landing State Historic Site`,
`Jewell Cemetery State Historic Site`,
`Locust Creek Covered Bridge State Historic Site`,
`Mark Twain Birthplace State Historic Site`,
`Mastodon State Historic Site`,
`Missouri Mines State Historic Site`,
`Missouri State Capitol`,
`Missouri State Museum`,
`Osage Village State Historic Site`,
`Sandy Creek Covered Bridge State Historic Site`,
`Sappington Cemetery State Historic Site`,
`Scott Joplin House State Historic Site`,
`Towosahgy State Historic Site`,
`Union Covered Bridge State Historic Site`,
`Watkins Woolen Mill State Historic Site`,
`Ackley Lake State Park`,
`Anaconda Smelter Stack State Park`,
`Bannack State Park`,
`Beaverhead Rock State Park`,
`Beavertail Hill State Park`,
`Big Arm State Park`,
`Black Sandy State Park`,
`Brush Lake State Park`,
`Chief Plenty Coups State Park`,
`Clark's Lookout State Park`,
`Cooney State Park`,
`Council Grove State Park`,
`Elkhorn State Park`,
`Finley Point State Park`,
`First Peoples Buffalo Jump State Park`,
`Fish Creek State Park`,
`Fort Owen State Park`,
`Frenchtown Pond State Park`,
`Giant Springs State Park`,
`Granite Ghost Town State Park`,
`Greycliff Prairie Dog Town State Park`,
`Hell Creek State Park`,
`Lake Elmo State Park`,
`Lake Mary Ronan State Park`,
`Les Mason State Park`,
`Lewis and Clark Caverns State Park`,
`Logan State Park`,
`Lone Pine State Park`,
`Lost Creek State Park`,
`Milltown State Park`,
`Madison Buffalo Jump State Park`,
`Makoshika State Park`,
`Marias River State Park`,
`Medicine Rocks State Park`,
`Missouri Headwaters State Park`,
`North Shore State Park`,
`Painted Rocks State Park`,
`Pictograph Cave State Park`,
`Pirogue Island State Park`,
`Placid Lake State Park`,
`Rosebud Battlefield State Park`,
`Salmon Lake State Park`,
`Sluice Boxes State Park`,
`Smith River State Park`,
`Spring Meadow Lake State Park`,
`Thompson Falls State Park`,
`Tongue River Reservoir State Park`,
`Tower Rock State Park`,
`Travelers' Rest State Park`,
`Wayfarers State Park`,
`West Shore State Park`,
`Whitefish Lake State Park`,
`Wild Horse Island State Park`,
`Yellow Bay State Park`,
`Chadron State Park`,
`Eugene T. Mahoney State Park`,
`Fort Robinson State Park`,
`Indian Cave State Park`,
`Niobrara State Park`,
`Platte River State Park`,
`Ponca State Park`,
`Smith Falls State Park`,
`Arbor Lodge State Historical Park`,
`Ash Hollow State Historical Park`,
`Ashfall Fossil Beds State Historical Park`,
`Bowring Ranch State Historical Park`,
`Buffalo Bill Ranch State Historical Park`,
`Fort Atkinson State Historical Park`,
`Fort Hartsuff State Historical Park`,
`Fort Kearny State Historical Park`,
`Rock Creek Station State Historical Park`,
`Beaver Dam State Park`,
`Berlin–Ichthyosaur State Park`,
`Big Bend of the Colorado State Recreation Area`,
`Cathedral Gorge State Park`,
`Cave Lake State Park`,
`Dayton State Park`,
`Echo Canyon State Park`,
`Elgin Schoolhouse State Historic Site`,
`Fort Churchill State Historic Park`,
`Kershaw–Ryan State Park`,
`Lahontan State Recreation Area`,
`Lake Tahoe – Nevada State Park`,
`Mormon Station State Historic Park`,
`Old Las Vegas Mormon Fort State Historic Park`,
`Rye Patch State Recreation Area`,
`South Fork State Recreation Area`,
`Spring Mountain Ranch State Park`,
`Spring Valley State Park`,
`Valley of Fire State Park`,
`Van Sickle Bi-State Park`,
`Ward Charcoal Ovens State Historic Park`,
`Washoe Lake State Park`,
`Wild Horse State Recreation Area`,
`Ahern State Park`,
`Androscoggin Wayside Park`,
`Annett Wayside Park`,
`Bear Brook State Park`,
`Beaver Brook Falls Wayside`,
`Cardigan Mountain State Park`,
`Chesterfield Gorge Natural Area`,
`Clough State Park`,
`Coleman State Park`,
`Crawford Notch State Park`,
`Deer Mountain Campground`,
`Dixville Notch State Park`,
`Echo Lake State Park`,
`Eisenhower Memorial Wayside Park`,
`Ellacoya State Park`,
`Forest Lake State Park`,
`Franconia Notch State Park`,
`Gardner Memorial Wayside Park`,
`Greenfield State Park`,
`Hampton Beach State Park`,
`Jenness State Beach`,
`Jericho Mountain State Park`,
`Kingston State Park`,
`Lake Francis State Park`,
`Lake Tarleton State Park`,
`Madison Boulder Natural Area`,
`Milan Hill State Park`,
`Miller State Park`,
`Mollidgewock State Park`,
`Monadnock State Park`,
`Moose Brook State Park`,
`Mount Sunapee State Park`,
`Mount Washington State Park`,
`Nansen Wayside Park`,
`North Hampton State Beach`,
`Northwood Meadows State Park`,
`Odiorne Point State Park`,
`Pawtuckaway State Park`,
`Pillsbury State Park`,
`Pisgah State Park`,
`Plummer's Ledge Natural Area`,
`Rhododendron State Park`,
`Rollins State Park`,
`Rye Harbor State Park`,
`Sculptured Rocks Natural Area`,
`Silver Lake State Park`,
`Umbagog Lake State Park`,
`Wadleigh State Park`,
`Wallis Sands State Beach`,
`Weeks State Park`,
`Wellington State Park`,
`Wentworth State Park`,
`White Lake State Park`,
`Winslow State Park`,
`Bedell Bridge State Historic Site`,
`Daniel Webster Birthplace State Historic Site`,
`Endicott Rock State Historic Site`,
`Fort Constitution State Historic Site`,
`Fort Stark State Historic Site`,
`Franklin Pierce Homestead State Historic Site`,
`Governor Wentworth Historic Site`,
`Hannah Duston Memorial State Historic Site`,
`John Wingate Weeks Historic Site`,
`Nansen Ski Jump State Historic Site`,
`Robert Frost Farm State Historic Site`,
`Taylor Mill State Historic Site`,
`Tip-Top House`,
`Wentworth–Coolidge Mansion State Historic Site`,
`White Island State Historic Site`,
`Willey House`,
`Bear's Den Natural Area`,
`Binney Pond Natural Area`,
`Bradford Pines Natural Area`,
`Crosby Mountain State Park`,
`Curtiss Dogwood Natural Area`,
`Dublin Lake Scenic Area`,
`Heath Pond Bog Natural Area`,
`Humphrey's Ledge Natural Area`,
`Jeremy Mill Natural Area`,
`Mascot Mine Natural Area`,
`Ossipee Lake Natural Area`,
`Otter Brook Lake`,
`Smith's Ferry Heritage Park`,
`Urban Forestry Center`,
`Wantastiquet Mountain Natural Area or Wantastiquet State Forest`,
`Allaire State Park`,
`Allamuchy Mountain State Park`,
`Barnegat Lighthouse State Park`,
`Cape May Point State Park`,
`Capital State Park`,
`Cheesequake State Park`,
`Corson's Inlet State Park`,
`Delaware and Raritan Canal State Park`,
`Double Trouble State Park`,
`Farny State Park`,
`Fort Mott State Park`,
`Hacklebarney State Park`,
`High Point State Park`,
`Hopatcong State Park`,
`Island Beach State Park`,
`Kittatinny Valley State Park`,
`Liberty State Park`,
`Long Pond Ironworks State Park`,
`Monmouth Battlefield State Park`,
`Parvin State Park`,
`Pigeon Swamp State Park`,
`Princeton Battlefield State Park`,
`Rancocas State Park`,
`Ringwood State Park`,
`Stephens State Park`,
`Swartswood State Park`,
`Tall Pines State Preserve`,
`Voorhees State Park`,
`Washington Crossing State Park`,
`Washington Rock State Park`,
`Wawayanda State Park`,
`Abram S. Hewitt State Forest`,
`Bass River State Forest`,
`Belleplain State Forest`,
`Brendan T. Byrne State Forest`,
`Jenny Jump State Forest`,
`Norvin Green State Forest`,
`Penn State Forest`,
`Ramapo Mountain State Forest`,
`Stokes State Forest`,
`Wharton State Forest`,
`Worthington State Forest`,
`Atsion Recreation Area`,
`Bull's Island Recreation Area`,
`Round Valley Recreation Area`,
`Spruce Run Recreation Area`,
`Warren Grove Recreation Area`,
`Senator Frank S. Farley State Marina`,
`Forked River State Marina`,
`Fortescue State Marina`,
`Leonardo State Marina`,
`Liberty Landing Marina`,
`Absecon Lighthouse`,
`Allaire Village`,
`Barnegat Lighthouse`,
`Batsto Village`,
`Blackwells Mills Canal House`,
`Boxwood Hall`,
`Cape May Light`,
`Central Railroad of New Jersey Terminal`,
`Clarke House`,
`Craig House`,
`Double Trouble Village`,
`Edison Memorial Tower and Museum`,
`Fort Mott`,
`Grover Cleveland Birthplace`,
`Hancock House`,
`The Hermitage`,
`High Point Monument`,
`Indian King Tavern`,
`Johnson Ferry House`,
`Long Pond Ironworks Historic District`,
`Monmouth Battlefield`,
`Mule Tenders Barracks`,
`Navesink Twin Lights`,
`Old Dutch Parsonage`,
`Port Mercer Canal House`,
`Prallsville Mills`,
`Princeton Battlefield`,
`Ringwood Manor`,
`Rockingham`,
`Skylands Manor & State Botanical Garden`,
`Somers Mansion`,
`Steuben House`,
`Trenton Battle Monument`,
`Wallace House`,
`Walt Whitman House`,
`Washington Crossing`,
`Waterloo Village`,
`Whitesbog Village`,
`Bluewater Lake State Park`,
`Bottomless Lakes State Park`,
`Brantley Lake State Park`,
`Caballo Lake State Park`,
`Cerrillos Hills State Park`,
`Cimarron Canyon State Park`,
`City of Rocks State Park`,
`Clayton Lake State Park`,
`Conchas Lake State Park`,
`Coyote Creek State Park`,
`Eagle Nest Lake State Park`,
`Elephant Butte Lake State Park`,
`El Vado Lake State Park`,
`Fenton Lake State Park`,
`Heron Lake State Park`,
`Hyde Memorial State Park`,
`Leasburg Dam State Park`,
`Living Desert Zoo and Gardens State Park`,
`Manzano Mountains State Park`,
`Mesilla Valley Bosque State Park`,
`Morphy Lake State Park`,
`Navajo Lake State Park`,
`Oasis State Park`,
`Oliver Lee Memorial State Park`,
`Pancho Villa State Park`,
`Percha Dam State Park`,
`Rio Grande Nature Center State Park`,
`Rockhound State Park`,
`Santa Rosa Lake State Park`,
`Storrie Lake State Park`,
`Sugarite Canyon State Park`,
`Sumner Lake State Park`,
`Ute Lake State Park`,
`Vietnam Veterans Memorial State Park`,
`Villanueva State Park`,
`Allan H. Treman State Marine Park`,
`Allegany State Park`,
`Amherst State Park`,
`Amsterdam Beach State Park`,
`Battle Island State Park`,
`Bayard Cutting Arboretum State Park`,
`Bayswater Point State Park`,
`Bear Mountain State Park`,
`Beaver Island State Park`,
`Beechwood State Park`,
`Belmont Lake State Park`,
`Bethpage State Park`,
`Betty and Wilbur Davis State Park`,
`Big Six Mile Creek Marina`,
`Blauvelt State Park`,
`Bonavista State Park Golf Course`,
`Bowman Lake State Park`,
`Braddock Bay State Park`,
`Brentwood State Park`,
`Bristol Beach State Park`,
`Brookhaven State Park`,
`Buckhorn Island State Park`,
`Buffalo Harbor State Park`,
`Burnham Point State Park`,
`Buttermilk Falls State Park`,
`Caleb Smith State Park Preserve`,
`Camp Hero State Park`,
`Canandaigua Lake State Marine Park`,
`Canoe-Picnic Point State Park`,
`Captree State Park`,
`Catharine Valley Trail`,
`Caumsett State Historic Park Preserve`,
`Cayuga Lake State Park`,
`Cedar Island State Park`,
`Cedar Point State Park`,
`Chenango Valley State Park`,
`Cherry Plain State Park`,
`Chimney Bluffs State Park`,
`Chittenango Falls State Park`,
`Clarence Fahnestock State Park`,
`Clark Reservation State Park`,
`Clay Pit Ponds State Park Preserve`,
`Cold Spring Harbor State Park`,
`Coles Creek State Park`,
`Conesus Lake Boat Launch`,
`Connetquot River State Park Preserve`,
`Crab Island State Park`,
`Croil Island State Park`,
`Cumberland Bay State Park`,
`Darien Lakes State Park`,
`De Veaux Woods State Park`,
`Deans Cove Boat Launch`,
`Delta Lake State Park`,
`Devil's Hole State Park`,
`Dewolf Point State Park`,
`Donald J. Trump State Park`,
`Earl W. Brydges Artpark State Park`,
`East River State Park`,
`Eel Weir State Park`,
`Evangola State Park`,
`Fair Haven Beach State Park`,
`Fillmore Glen State Park`,
`Fort Niagara State Park`,
`Four Mile Creek State Park`,
`Franklin D. Roosevelt State Park`,
`Franklin D. Roosevelt Four Freedoms Park`,
`Franny Reese State Park`,
`Galop Island State Park`,
`Gantry Plaza State Park`,
`Genesee Valley Greenway`,
`Gilbert Lake State Park`,
`Gilgo State Park`,
`Glimmerglass State Park`,
`Golden Hill State Park`,
`Goosepond Mountain State Park`,
`Grafton Lakes State Park`,
`Grass Point State Park`,
`Green Lakes State Park`,
`Hallock State Park Preserve`,
`Hamlin Beach State Park`,
`Harriet Hollister Spencer State Recreation Area`,
`Harriman State Park`,
`Hart's Brook Nature Preserve`,
`Haverstraw Beach State Park`,
`Heckscher State Park`,
`Helen L. McNitt State Park`,
`Hempstead Lake State Park`,
`High Tor State Park`,
`Highland Lakes State Park`,
`Higley Flow State Park`,
`Hither Hills State Park`,
`Honeoye Lake Boat Launch State Park`,
`Hook Mountain State Park`,
`Hudson Highlands State Park`,
`Hudson River Islands State Park`,
`Hudson River Park`,
`Iona Island State Park`,
`Irondequoit Bay State Marine Park`,
`Jacques Cartier State Park`,
`James Baird State Park`,
`Jay Estate`,
`John Boyd Thacher State Park`,
`Jones Beach State Park`,
`Joseph Davis State Park`,
`Keewaydin State Park`,
`Keuka Lake State Park`,
`Knox Farm State Park`,
`Kring Point State Park`,
`Lake Erie State Park`,
`Lake Lauderdale State Park`,
`Lake Superior State Park`,
`Lake Taghkanic State Park`,
`Lakeside Beach State Park`,
`Letchworth State Park`,
`Lock 32 State Canal Park`,
`Lodi Point State Park`,
`Long Point State Park - Finger Lakes`,
`Long Point State Park - Thousand Islands`,
`Long Point State Park on Lake Chautauqua`,
`Macomb Reservation State Park`,
`Margaret Lewis Norrie State Park`,
`Mark Twain State Park and Soaring Eagles Golf Course`,
`Mary Island State Park`,
`Max V. Shaul State Park`,
`Mexico Point State Park`,
`Mexico Point Boat Launch`,
`Midway State Park`,
`Mine Kill State Park`,
`Miner Lake State Park`,
`Minnewaska State Park Preserve`,
`Mohawk River State Park`,
`Montauk Downs State Park`,
`Montauk Point State Park`,
`Moreau Lake State Park`,
`Napeague State Park`,
`Newtown Battlefield State Park`,
`Niagara Falls State Park`,
`Nissequogue River State Park`,
`Nyack Beach State Park`,
`Oak Orchard State Marine Park`,
`Ogden Mills & Ruth Livingston Mills State Park`,
`Old Croton Aqueduct State Historic Park`,
`Old Erie Canal State Historic Park`,
`Oquaga Creek State Park`,
`Orient Beach State Park`,
`Peebles Island State Park`,
`Pinnacle State Park and Golf Course`,
`Pixley Falls State Park`,
`Point Au Roche State Park`,
`Reservoir State Park`,
`Riverbank State Park`,
`Robert Moses State Park (Long Island)`,
`Robert Moses State Park (Thousand Islands)`,
`Robert V. Riddell State Park`,
`Robert H. Treman State Park`,
`Robert G. Wehle State Park`,
`Roberto Clemente State Park`,
`Rock Island Lighthouse State Park`,
`Rockefeller State Park Preserve`,
`Rockland Lake State Park`,
`St. Lawrence State Park Golf Course`,
`Sampson State Park`,
`Sandy Island Beach State Park`,
`Saratoga Lake State Boat Launch`,
`Saratoga Spa State Park`,
`Schodack Island State Park`,
`Schunnemunk State Park`,
`Selkirk Shores State Park`,
`Seneca Lake State Park`,
`Shadmoor State Park`,
`Shirley Chisholm State Park`,
`Silver Lake State Park`,
`Sonnenberg Gardens & Mansion State Historic Park`,
`Southwick Beach State Park`,
`State Park at the Fair`,
`Sterling Forest State Park`,
`Stony Brook State Park`,
`Storm King State Park`,
`Strawberry Island State Park`,
`Sunken Meadow State Park`,
`Taconic State Park – Copake Falls area`,
`Taconic State Park – Rudd Pond area`,
`Tallman Mountain State Park`,
`Taughannock Falls State Park`,
`Thompson's Lake State Park`,
`Trail View State Park`,
`Two Rivers State Park Recreation Area`,
`Valley Stream State Park`,
`Verona Beach State Park`,
`Walkway Over the Hudson State Historic Park`,
`Waterson Point State Park`,
`Watkins Glen State Park`,
`Wellesley Island State Park`,
`Westcott Beach State Park`,
`Whetstone Gulf State Park`,
`Whirlpool State Park`,
`Wildwood State Park`,
`Wilson-Tuscarora State Park`,
`Wonder Lake State Park`,
`Woodlawn Beach State Park`,
`Beaver Lake State Park`,
`Butte Saint Paul State Recreation Area`,
`Cross Ranch State Park`,
`Crow Flies High State Recreation Area`,
`Fort Abraham Lincoln State Park`,
`Fort Ransom State Park`,
`Fort Stevenson State Park`,
`Grahams Island State Park`,
`Icelandic State Park`,
`Lake Metigoshe State Park`,
`Lake Sakakawea State Park`,
`Lewis and Clark State Park`,
`Little Metigoshe State Recreation Area`,
`Little Missouri State Park`,
`Pelican Point State Recreation Area`,
`Pembina Gorge State Recreation Area`,
`Sully Creek State Park`,
`Turtle River State Park`,
`A. W. Marion State Park`,
`Adams Lake State Park`,
`Alum Creek State Park`,
`Barkcamp State Park`,
`Beaver Creek State Park`,
`Blue Rock State Park`,
`Buck Creek State Park`,
`Buckeye Lake State Park`,
`Burr Oak State Park`,
`Caesar Creek State Park`,
`Catawba Island State Park`,
`Cowan Lake State Park`,
`Deer Creek State Park`,
`Delaware State Park`,
`Dillon State Park`,
`East Fork State Park`,
`East Harbor State Park`,
`Findley State Park`,
`Forked Run State Park`,
`Geneva State Park`,
`Grand Lake St. Marys State Park`,
`Great Seal State Park`,
`Guilford Lake State Park`,
`Harrison Lake State Park`,
`Headlands Beach State Park`,
`Hocking Hills State Park`,
`Hueston Woods State Park`,
`Independence Dam State Park`,
`Indian Lake State Park`,
`Jackson Lake State Park`,
`Jefferson Lake State Park`,
`John Bryan State Park`,
`Kelleys Island State Park`,
`Kiser Lake State Park`,
`Lake Alma State Park`,
`Lake Hope State Park`,
`Lake Logan State Park`,
`Lake Loramie State Park`,
`Lake White State Park`,
`Little Miami State Park`,
`Madison Lake State Park`,
`Malabar Farm State Park`,
`Mary Jane Thurston State Park`,
`Maumee Bay State Park`,
`Mohican State Park`,
`Mosquito Lake State Park`,
`Mount Gilead State Park`,
`Nelson Kennedy Ledges State Park`,
`Oak Point State Park`,
`Paint Creek State Park`,
`Pike Lake State Park`,
`Portage Lakes State Park`,
`Punderson State Park`,
`Pymatuning State Park`,
`Quail Hollow State Park`,
`Rocky Fork State Park`,
`Salt Fork State Park`,
`Scioto Trail State Park`,
`Shawnee State Park`,
`South Bass Island State Park`,
`Spiegel Grove State Park`,
`Stonelick State Park`,
`Strouds Run State Park`,
`Sycamore State Park`,
`Tar Hollow State Park`,
`Tinker's Creek State Park`,
`Van Buren State Park`,
`West Branch State Park`,
`Wolf Run State Park`,
`Adena State Memorial`,
`Buckeye Furnace State Memorial`,
`Campbell Mound State Memorial`,
`Flint Ridge State Memorial`,
`Friends Meeting House State Memorial`,
`Fort Ancient State Memorial, Warren County`,
`Fort Hill State Memorial`,
`Glendower State Memorial, Warren County`,
`Leo Petroglyph State Memorial`,
`Miamisburg Mound State Memorial, Montgomery County`,
`Serpent Mound State Memorial`,
`Tarleton Cross Mound State Memorial`,
`Fox Lake Wildlife Management Area (Athens County)`,
`Highlandtown Wildlife Area (Columbiana County, Washington Township)`,
`Milan State Wildlife Area`,
`Sunday Creek Wildlife Management Area (Athens County)`,
`Tiffin River Wildlife Area (Fulton County)`,
`Trimble Wildlife Management Area (Athens County)`,
`Turkey Ridge Wildlife Area (Vinton County)`,
`Waterloo Wildlife Research Station (Athens County)`,
`Wolf Creek Wildlife Management Area (Morgan County)`,
`Acadia Cliffs State Nature Preserve`,
`Adams Lake Prairie State Nature Preserve`,
`Audubon Islands State Nature Preserve`,
`Aurora Sanctuary State Nature Preserve`,
`Baker Woods State Nature Preserve`,
`Bigelow Cemetery Prairie State Nature Preserve`,
`Blackhand Gorge State Nature Preserve`,
`Boord State Nature Preserve`,
`Brown's Lake Bog State Nature Preserve`,
`Burton Wetlands State Nature Preserve`,
`Caesar Creek Gorge State Nature Preserve`,
`Carmean Woods State Nature Preserve`,
`Cedar Bog State Nature Preserve`,
`Chaparral Prairie State Nature Preserve`,
`Clear Creek State Nature Preserve`,
`Clear Fork Gorge State Nature Preserve`,
`Clifton Gorge State Nature Preserve`,
`Collier State Nature Preserve`,
`Compass Plant Prairie State Nature Preserve`,
`Conkle's Hollow State Nature Preserve`,
`Conneaut Swamp State Nature Preserve`,
`Cranberry Bog State Nature Preserve`,
`Crooked Run State Nature Preserve`,
`Culberson Woods State Nature Preserve`,
`Davey Woods State Nature Preserve`,
`Davis Memorial State Nature Preserve`,
`Drew Woods State Nature Preserve`,
`Dupont Marsh State Nature Preserve`,
`Eagle Creek State Nature Preserve`,
`Erie Sand Barrens State Nature Preserve`,
`Fowler Woods State Nature Preserve`,
`Gahanna Woods State Nature Preserve`,
`Goll Woods State Nature Preserve`,
`Goode Prairie State Nature Preserve`,
`Greenville Falls State Nature Preserve`,
`Gross Woods State Nature Preserve`,
`Hach-Otis State Nature Preserve`,
`Halls Creek Woods State Nature Preserve`,
`Headlands Dunes State Nature Preserve`,
`Herrick Fen State Nature Preserve`,
`Hueston Woods State Nature Preserve`,
`Hutchins (Highbanks) State Nature Preserve`,
`Irwin Prairie State Nature Preserve`,
`Jackson Bog State Nature Preserve`,
`Johnson Ridge State Nature Preserve`,
`Johnson Woods State Nature Preserve`,
`Kendrick Woods State Nature Preserve`,
`Kent (Cooperrider) Bog State Nature Preserve`,
`Kessler Swamp State Nature Preserve`,
`Kiser Lake Wetlands State Nature Preserve`,
`Kitty Todd State Nature Preserve`,
`Knox Woods State Nature Preserve`,
`Kyle Woods State Nature Preserve`,
`Lake Katharine State Nature Preserve`,
`Lakeside Daisy State Nature Preserve`,
`Lawrence Woods State Nature Preserve`,
`Lou Campbell State Nature Preserve`,
`Mantua Bog State Nature Preserve`,
`Marie J. Desonier State Nature Preserve`,
`Marsh Wetlands State Nature Preserve`,
`Mentor Marsh State Nature Preserve`,
`Milford Center Prairie State Nature Preserve`,
`Morris Woods State Nature Preserve`,
`North Pond State Nature Preserve`,
`North Shore Alvar State Nature Preserve`,
`Novak State Nature Preserve`,
`Old Woman Creek State Nature Preserve`,
`Olsen (Augusta-Anne) State Nature Preserve`,
`Pickerington Ponds State Nature Preserve`,
`Portage Lakes Wetland State Nature Preserve`,
`Riddle State Nature Preserve`,
`Rockbridge State Nature Preserve`,
`Sears Woods State Nature Preserve`,
`Seymour Woods State Nature Preserve`,
`Shallenberger State Nature Preserve`,
`Sharon Woods Gorge State Nature Preserve`,
`Sheepskin Hollow State Nature Preserve`,
`Sheldon Marsh State Nature Preserve`,
`Shoemaker State Nature Preserve`,
`Siegenthaler-Kaestner Esker State Nature Preserve`,
`Smith Cemetery Prairie State Nature Preserve`,
`Springville Marsh State Nature Preserve`,
`Stage's Pond State Nature Preserve`,
`Stratford Woods State Nature Preserve`,
`Swamp Cottonwood State Nature Preserve`,
`Thomas (Sharon Woods) State Nature Preserve`,
`Tinker's Creek State Nature Preserve`,
`Triangle Lake Bog State Nature Preserve`,
`Tucker (Blacklick) State Nature Preserve`,
`Tummonds State Nature Preserve`,
`Wahkeena State Nature Preserve`,
`Whipple State Nature Preserve`,
`Zimmerman Prairie State Nature Preserve`,
`Alabaster Caverns State Park`,
`Arrowhead State Park`,
`Beavers Bend State Park`,
`Bernice State Park`,
`Black Mesa State Park`,
`Boiling Springs State Park`,
`Cherokee Landing State Park`,
`Cherokee State Park`,
`Clayton Lake State Park`,
`Disney/Little Blue State Park`,
`Fort Cobb State Park`,
`Foss State Park`,
`Gloss Mountain State Park`,
`Great Plains State Park`,
`Great Salt Plains State Park`,
`Greenleaf State Park`,
`Honey Creek State Park`,
`Hugo Lake State Park`,
`Keystone State Park`,
`Lake Eufaula State Park`,
`Lake Murray State Park`,
`Lake Texoma State Park`,
`Lake Thunderbird State Park`,
`Lake Wister State Park`,
`Little Sahara State Park`,
`McGee Creek State Park`,
`Natural Falls State Park`,
`Osage Hills State Park`,
`Raymond Gary State Park`,
`Robbers Cave State Park`,
`Roman Nose State Park`,
`Sequoyah Bay State Park`,
`Sequoyah/Western Hills State Park`,
`Spavinaw State Park`,
`Talimena State Park`,
`Tenkiller State Park`,
`Twin Bridges State Park`,
`Goose Lake State Recreation Area`,
`Frenchglen Hotel State Heritage Site`,
`Ontario State Recreation Site`,
`Farewell Bend State Recreation Area`,
`Kam Wah Chung State Heritage Site`,
`Unity Forest State Scenic Corridor`,
`Unity Lake State Recreation Site`,
`Clyde Holliday State Recreation Site`,
`Succor Creek State Natural Area`,
`Lake Owyhee State Park`,
`Catherine Creek State Park`,
`Hat Rock State Park`,
`Hilgard Junction State Recreation Area`,
`Red Bridge State Wayside`,
`Ukiah–Dale Forest State Scenic Corridor`,
`Emigrant Springs State Heritage Area`,
`Wallowa Lake Highway Forest State Scenic Corridor`,
`Wallowa River Rest Area`,
`Minam State Recreation Area`,
`Wallowa Lake State Recreation Area`,
`Iwetemlaykin State Heritage Site`,
`Casey State Recreation Site`,
`Prospect State Scenic Viewpoint`,
`Joseph H. Stewart State Recreation Area`,
`The Cove Palisades State Park`,
`Jasper Point Campground`,
`Prineville Reservoir State Park`,
`Heritage Landing (Deschutes)`,
`White River Falls State Park`,
`Deschutes River State Recreation Area`,
`Cline Falls State Scenic Viewpoint`,
`Fort Rock State Natural Area`,
`La Pine State Park`,
`Pilot Butte State Scenic Viewpoint`,
`Tumalo State Park`,
`Peter Skene Ogden State Scenic Viewpoint`,
`Smith Rock State Park`,
`Booth State Scenic Corridor`,
`Chandler State Wayside`,
`Geisel Monument State Heritage Site`,
`Humbug Mountain State Park`,
`Otter Point State Recreation Site`,
`Paradise Point State Recreation Site`,
`Port Orford Heads State Park`,
`Cape Blanco State Park`,
`Bandon State Natural Area`,
`Coquille Myrtle Grove State Natural Site`,
`Face Rock State Scenic Viewpoint`,
`Hoffman Memorial State Wayside`,
`Seven Devils State Recreation Site`,
`Bullards Beach State Park`,
`Alfred A. Loeb State Park`,
`Cape Sebastian State Scenic Corridor`,
`Crissey Field State Recreation Site`,
`McVay Rock State Recreation Site`,
`Pistol River State Scenic Viewpoint`,
`Samuel H. Boardman State Scenic Corridor`,
`Winchuck State Recreation Site`,
`Harris Beach State Recreation Area`,
`Alderwood State Wayside`,
`Elijah Bristow State Park`,
`Washburne State Wayside`,
`Maples Rest Area`,
`Mongold Day-Use Area`,
`North Santiam State Recreation Area`,
`Detroit Lake State Recreation Area`,
`Cape Arago State Park`,
`Golden and Silver Falls State Natural Area`,
`Shore Acres State Park`,
`William M. Tugman State Park`,
`Sunset Bay State Park`,
`Illinois River Forks State Park`,
`TouVelle State Recreation Site`,
`Tub Springs State Wayside`,
`Wolf Creek Inn State Heritage Site`,
`Valley of the Rogue State Recreation Area`,
`Bald Peak State Scenic Viewpoint`,
`Molalla River State Park`,
`Champoeg State Heritage Area`,
`Beaver Creek State Natural Area`,
`Bolon Island Tideways State Scenic Corridor`,
`Darlingtonia State Natural Site`,
`Governor Patterson Memorial State Recreation Site`,
`Umpqua Lighthouse State Park`,
`Beachside State Recreation Site`,
`Carl G. Washburne Memorial State Park`,
`Heceta Head Lighthouse State Scenic Viewpoint`,
`Muriel O. Ponsler Memorial State Scenic Viewpoint`,
`Neptune State Scenic Viewpoint`,
`Smelt Sands State Recreation Site`,
`Tokatee Klootchman State Natural Site`,
`Stonefield Beach State Recreation Site`,
`W. B. Nelson State Recreation Site`,
`Yachats Ocean Road State Natural Site`,
`Yachats State Recreation Area`,
`Jessie M. Honeyman Memorial State Park`,
`Erratic Rock State Natural Site`,
`Holman State Wayside`,
`Maud Williamson State Recreation Site`,
`Sarah Helmick State Recreation Site`,
`Willamette Mission State Park`,
`Bonnie Lure State Recreation Area`,
`Mary S. Young State Recreation Area`,
`Milo McIver State Park`,
`Tryon Creek State Natural Area`,
`Banks–Vernonia State Trail`,
`Ainsworth State Park`,
`Benson State Recreation Area`,
`Bridal Veil Falls State Scenic Viewpoint`,
`Crown Point State Scenic Corridor`,
`Dabney State Recreation Area`,
`George W. Joseph State Natural Area (accessible from Guy W. Talbot State Park)`,
`Guy W. Talbot State Park`,
`Historic Columbia River Highway State Trail`,
`John B. Yeon State Scenic Corridor`,
`Koberg Beach State Recreation Site`,
`Lewis and Clark State Recreation Site`,
`Mayer State Park`,
`Memaloose State Park`,
`Portland Women's Forum State Scenic Viewpoint`,
`Seneca Fouts Memorial State Natural Area`,
`Shepperd's Dell State Natural Area`,
`Sheridan State Scenic Corridor`,
`Starvation Creek State Park`,
`Viento State Park`,
`Vinzenz Lausmann Memorial State Natural Area`,
`Wygant State Natural Area`,
`Rooster Rock State Park`,
`Bradley State Scenic Viewpoint`,
`Del Rey Beach State Recreation Site`,
`Fort Stevens State Park`,
`Cape Kiwanda State Natural Area`,
`Cape Meares State Scenic Viewpoint`,
`Oceanside Beach State Recreation Site`,
`Bob Straub State Park`,
`Cape Lookout State Park`,
`Arcadia Beach State Recreation Site`,
`Ecola State Park`,
`Golden State Heritage Site`,
`Hug Point State Recreation Site`,
`Manhattan Beach State Recreation Site`,
`Oswald West State Park`,
`Saddle Mountain State Natural Area`,
`Tolovana Beach State Recreation Site`,
`Nehalem Bay State Park`,
`Alsea Bay Historic Interpretive Center`,
`Driftwood Beach State Recreation Site`,
`Lost Creek State Recreation Site`,
`Ona Beach State Park`,
`Seal Rock State Recreation Site`,
`Yaquina Bay State Recreation Site`,
`South Beach State Park`,
`Cascadia State Park`,
`Silver Falls State Park`,
`Agate Beach State Recreation Site`,
`Boiler Bay State Scenic Viewpoint`,
`D River State Recreation Site`,
`Devils Lake State Recreation Area`,
`Devils Punch Bowl State Natural Area`,
`Ellmaker State Wayside`,
`Fogarty Creek State Recreation Area`,
`Gleneden Beach State Recreation Site`,
`H. B. Van Duzer Forest State Scenic Corridor`,
`Neskowin Beach State Recreation Site`,
`Otter Crest State Scenic Viewpoint`,
`Roads End State Recreation Site`,
`Beverly Beach State Park`,
`Collier Memorial State Park`,
`Jackson F. Kimball State Recreation Site`,
`OC&E Woods Line State Trail`,
`South Jetty (South Beach)`,
`Blue Mountain Forest State Scenic Corridor`,
`Battle Mountain Forest State Scenic Corridor`,
`Sumpter Valley Dredge State Heritage Area`,
`Fall Creek State Recreation Site`,
`Lowell State Recreation Site`,
`Jasper State Recreation Site`,
`Dexter State Recreation Site`,
`Munson Creek Falls State Natural Site`,
`Willamette Stone State Heritage Site`,
`Umpqua State Scenic Corridor`,
`Clay Myers State Natural Area at Whalen Island`,
`Fort Rock Cave (Near Fort Rock State Natural Area)`,
`Government Island State Recreation Area`,
`Sunset Beach State Recreation Site`,
`Whale Watching Center`,
`Rocky Creek State Scenic Viewpoint`,
`Fort Yamhill State Heritage Area`,
`L. L. "Stub" Stewart State Park`,
`Thompson's Mills State Heritage Site`,
`State Capitol State Park`,
`Arizona Beach State Recreation Site`,
`Bates State Park`,
`Ochoco State Scenic Viewpoint`,
`Dyer State Wayside`,
`Pete French Round Barn State Heritage Site`,
`Cottonwood Canyon State Park`,
`Sitka Sedge State Natural Area`,
`Allegheny Islands State Park`,
`Archbald Pothole State Park`,
`Bald Eagle State Park`,
`Beltzville State Park`,
`Bendigo State Park`,
`Benjamin Rush State Park`,
`Big Pocono State Park`,
`Big Spring State Forest Picnic Area`,
`Black Moshannon State Park`,
`Blue Knob State Park`,
`Boyd Big Tree Preserve Conservation Area`,
`Buchanan's Birthplace State Park`,
`Bucktail State Park Natural Area`,
`Caledonia State Park`,
`Canoe Creek State Park`,
`Chapman State Park`,
`Cherry Springs State Park`,
`Clear Creek State Park`,
`Codorus State Park`,
`Colonel Denning State Park`,
`Colton Point State Park`,
`Cook Forest State Park`,
`Cowans Gap State Park`,
`Delaware Canal State Park`,
`Denton Hill State Park`,
`Elk State Park`,
`Erie Bluffs State Park`,
`Evansburg State Park`,
`Fort Washington State Park`,
`Fowlers Hollow State Park`,
`Frances Slocum State Park`,
`French Creek State Park`,
`Gifford Pinchot State Park`,
`Gouldsboro State Park`,
`Greenwood Furnace State Park`,
`Hickory Run State Park`,
`Hillman State Park`,
`Hills Creek State Park`,
`Hyner Run State Park`,
`Hyner View State Park`,
`Jacobsburg Environmental Education Center`,
`Jennings Environmental Education Center`,
`Joseph E. Ibberson Conservation Area`,
`Kettle Creek State Park`,
`Keystone State Park`,
`Kings Gap Environmental Education and Training Center`,
`Kinzua Bridge State Park`,
`Kooser State Park`,
`Lackawanna State Park`,
`Laurel Hill State Park`,
`Laurel Mountain State Park`,
`Laurel Ridge State Park`,
`Laurel Summit State Park`,
`Lehigh Gorge State Park`,
`Leonard Harrison State Park`,
`Linn Run State Park`,
`Little Buffalo State Park`,
`Little Pine State Park`,
`Locust Lake State Park`,
`Lyman Run State Park`,
`Marsh Creek State Park`,
`Maurice K. Goddard State Park`,
`McCalls Dam State Park`,
`McConnells Mill State Park`,
`Memorial Lake State Park`,
`Milton State Park`,
`Mont Alto State Park`,
`Moraine State Park`,
`Mt. Pisgah State Park`,
`Nescopeck State Park`,
`Neshaminy State Park`,
`Nockamixon State Park`,
`Nolde Forest Environmental Education Center`,
`Norristown Farm Park`,
`Ohiopyle State Park`,
`Oil Creek State Park`,
`Ole Bull State Park`,
`Parker Dam State Park`,
`Patterson State Park`,
`Penn-Roosevelt State Park`,
`Pine Grove Furnace State Park`,
`Poe Paddy State Park`,
`Poe Valley State Park`,
`Point State Park`,
`Presque Isle State Park`,
`Prince Gallitzin State Park`,
`Promised Land State Park`,
`Prompton State Park`,
`Prouty Place State Park`,
`Pymatuning State Park`,
`R. B. Winter State Park`,
`Raccoon Creek State Park`,
`Ralph Stover State Park`,
`Ravensburg State Park`,
`Reeds Gap State Park`,
`Ricketts Glen State Park`,
`Ridley Creek State Park`,
`Ryerson Station State Park`,
`S. B. Elliott State Park`,
`Salt Springs State Park`,
`Samuel S. Lewis State Park`,
`Sand Bridge State Park`,
`Shawnee State Park`,
`Shikellamy State Park`,
`Sinnemahoning State Park`,
`Sizerville State Park`,
`Susquehanna State Park`,
`Susquehannock State Park`,
`Swatara State Park`,
`Tobyhanna State Park`,
`Trough Creek State Park`,
`Tuscarora State Park`,
`Tyler State Park`,
`Upper Pine Bottom State Park`,
`Varden Conservation Area`,
`Warriors Path State Park`,
`Washington Crossing Historic Park`,
`Whipple Dam State Park`,
`White Clay Creek Preserve`,
`Worlds End State Park`,
`Yellow Creek State Park`,
`Beavertail State Park`,
`Blackstone River Bikeway State Park`,
`Brenton Point State Park`,
`Burlingame State Park`,
`Colt State Park`,
`Fishermen's Memorial State Park`,
`Fort Adams State Park`,
`Fort Wetherill State Park`,
`Goddard Memorial State Park`,
`Haines Memorial State Park`,
`Lincoln Woods State Park`,
`Pulaski State Park`,
`Rocky Point State Park`,
`Snake Den State Park`,
`World War II Memorial State Park`,
`Charlestown Breachway State Beach`,
`East Beach State Beach`,
`East Matunuck State Beach`,
`Misquamicut State Beach`,
`Roger Wheeler State Beach`,
`Salty Brine State Beach`,
`Scarborough State Beaches`,
`Arcadia Management Area`,
`Beach Pond`,
`East Bay Bike Path State Park`,
`George Washington State Campground`,
`John H. Chafee Nature Preserve`,
`Adams Homestead and Nature Preserve`,
`Angostura Recreation Area`,
`Bear Butte State Park`,
`Beaver Creek Nature Area`,
`Big Sioux Recreation Area`,
`Big Stone Island Nature Area`,
`Burke Lake Recreation Area`,
`Buryanek Recreation Area`,
`Chief White Crane Recreation Area`,
`Cow Creek Recreation Area`,
`Custer State Park`,
`Farm Island Recreation Area`,
`Fisher Grove State Park`,
`Fort Sisseton Historic State Park`,
`George S. Mickelson Trail`,
`Good Earth State Park at Blood Run`,
`Hartford Beach State Park`,
`Indian Creek Recreation Area`,
`LaFramboise Island Nature Area`,
`Lake Alvin Recreation Area`,
`Lake Cochrane Recreation Area`,
`Lake Herman State Park`,
`Lake Hiddenwood Recreation Area`,
`Lake Louise Recreation Area`,
`Lake Poinsett Recreation Area`,
`Lake Thompson Recreation Area`,
`Lake Vermillion Recreation Area`,
`Lewis & Clark Recreation Area`,
`Little Moreau Recreation Area`,
`Llewellyn Johns Recreation Area`,
`Mina Lake Recreation Area`,
`Newton Hills State Park`,
`North Point Recreation Area`,
`North Wheeler Recreation Area`,
`Oahe Downstream Recreation Area`,
`Oakwood Lakes State Park`,
`Okobojo Point Recreation Area`,
`Palisades State Park`,
`Pease Creek Recreation Area`,
`Pelican Lake Recreation Area`,
`Pickerel Lake Recreation Area`,
`Pierson Ranch Recreation Area`,
`Platte Creek Recreation Area`,
`Randall Creek Recreation Area`,
`Revheim Bay Recreation Area`,
`Richmond Lake Recreation Area`,
`Rocky Point Recreation Area`,
`Roughlock Falls Nature Area`,
`Roy Lake State Park`,
`Sandy Shore Recreation Area`,
`Shadehill Recreation Area`,
`Sheps Canyon Recreation Area`,
`Sica Hollow State Park`,
`Snake Creek Recreation Area`,
`Spirit Mound Historic Prairie`,
`Spring Creek Recreation Area`,
`Springfield Recreation Area`,
`Swan Creek Recreation Area`,
`Union Grove State Park`,
`Walkers Point Recreation Area`,
`West Bend Recreation Area`,
`West Pollock Recreation Area`,
`West Whitlock Recreation Area`,
`Alburg Dunes State Park`,
`Allis State Park`,
`Big Deer State Park`,
`Bomoseen State Park`,
`Boulder Beach State Park`,
`Branbury State Park`,
`Brighton State Park`,
`Burton Island State Park`,
`Button Bay State Park`,
`Camel's Hump State Park`,
`Camp Plymouth State Park`,
`Coolidge State Park`,
`Crystal Lake State Park`,
`D.A.R. State Park`,
`D&H Rail Trail`,
`Elmore State Park`,
`Emerald Lake State Park`,
`Fort Dummer State Park`,
`Gifford Woods State Park`,
`Grand Isle State Park`,
`Green River Reservoir State Park`,
`Half Moon Pond State Park`,
`Hazen's Notch State Park`,
`Jamaica State Park`,
`Kamp Kill Kare State Park`,
`Kettle Pond State Park`,
`Kingsland Bay State Park`,
`Knight Island State Park`,
`Knight Point State Park`,
`Lake Carmi State Park`,
`Lake St. Catherine State Park`,
`Lake Shaftsbury State Park`,
`Little River State Park`,
`Lowell Lake State Park`,
`Maidstone State Park`,
`Molly Stark State Park`,
`Molly's Falls Pond State Park`,
`Mount Ascutney State Park`,
`Mount Philo State Park`,
`Muckross State Park`,
`New Discovery State Park`,
`Niquette Bay State Park`,
`North Hero State Park`,
`Quechee State Park`,
`Ricker Pond State Park`,
`Sand Bar State Park`,
`Sentinel Rock State Park`,
`Seyon Lodge State Park`,
`Silver Lake State Park`,
`Smugglers' Notch State Park`,
`Stillwater State Park`,
`Sweet Pond State Park`,
`Taconic Mountains Ramble State Park`,
`Thetford Hill State Park`,
`Townshend State Park`,
`Underhill State Park`,
`Waterbury Center State Park`,
`Wilgus State Park`,
`Woodford State Park`,
`Woods Island State Park`,
`Alta Lake State Park`,
`Anderson Lake State Park`,
`Battle Ground Lake State Park`,
`Bay View State Park`,
`Beacon Rock State Park`,
`Belfair State Park`,
`Birch Bay State Park`,
`Blake Island State Park`,
`Blind Island State Park`,
`Bogachiel State Park`,
`Bottle Beach State Park`,
`Bridgeport State Park`,
`Bridle Trails State Park`,
`Brooks Memorial State Park`,
`Cama Beach State Park`,
`Camano Island State Park`,
`Cape Disappointment State Park`,
`Centennial Trail State Park`,
`Clark Island State Park`,
`Columbia Hills State Park`,
`Columbia Plateau Trail State Park`,
`Conconully State Park`,
`Crawford State Park`,
`Curlew Lake State Park`,
`Cutts Island State Park`,
`Daroga State Park`,
`Dash Point State Park`,
`Deception Pass State Park`,
`Doe Island State Park`,
`Dosewallips State Park`,
`Doug's Beach State Park`,
`Eagle Island State Park`,
`Federation Forest State Park`,
`Fields Spring State Park`,
`Flaming Geyser State Park`,
`Fort Casey State Park`,
`Fort Columbia State Park`,
`Fort Ebey State Park`,
`Fort Flagler State Park`,
`Fort Simcoe State Park`,
`Fort Townsend State Park`,
`Fort Worden State Park`,
`Ginkgo Petrified Forest State Park/Wanapum Recreational Area`,
`Goldendale Observatory State Park`,
`Grayland Beach State Park`,
`Griffiths-Priday Ocean State Park`,
`Harstine Island State Park`,
`Hope Island State Park (Mason County)`,
`Hope Island State Park (Skagit County)`,
`Ike Kinswa State Park`,
`Illahee State Park`,
`Iron Horse State Park`,
`James Island State Park`,
`Jarrell Cove State Park`,
`Joemma Beach State Park`,
`Jones Island State Park`,
`Joseph Whidbey State Park`,
`Kanaskat-Palmer State Park`,
`Kinney Point State Park`,
`Kitsap Memorial State Park`,
`Kopachuck State Park`,
`Lake Chelan State Park`,
`Lake Easton State Park`,
`Lake Isabella State Park`,
`Lake Sammamish State Park`,
`Lake Sylvia State Park`,
`Lake Wenatchee State Park`,
`Larrabee State Park`,
`Leadbetter Point State Park`,
`Lewis and Clark State Park`,
`Lewis and Clark Trail State Park`,
`Lime Kiln Point State Park`,
`Lincoln Rock State Park`,
`Lyons Ferry Park`,
`Loomis Lake State Park`,
`Manchester State Park`,
`Maryhill State Park`,
`Matia Island State Park`,
`McMicken Island State Park`,
`Millersylvania State Park`,
`Moran State Park`,
`Mount Pilchuck State Park`,
`Mount Spokane State Park`,
`Mystery Bay State Park`,
`Nolte State Park`,
`Obstruction Pass State Park`,
`Ocean City State Park`,
`Olallie State Park`,
`Olmstead Place State Park`,
`Pacific Beach State Park`,
`Pacific Pines State Park`,
`Palouse Falls State Park`,
`Paradise Point State Park`,
`Patos Island State Park`,
`Peace Arch State Park`,
`Pearrygin Lake State Park`,
`Penrose Point State Park`,
`Peshastin Pinnacles State Park`,
`Pleasant Harbor State Park`,
`Posey Island State Park`,
`Potholes State Park`,
`Potlatch State Park`,
`Rainbow Falls State Park`,
`Rasar State Park`,
`Reed Island State Park`,
`Riverside State Park`,
`Rockport State Park`,
`Rothschild House State Park`,
`Sacajawea State Park`,
`Saddlebag Island State Park`,
`Saint Edward State Park`,
`Saltwater State Park`,
`Scenic Beach State Park`,
`Schafer State Park`,
`Seaquest State Park`,
`Sequim Bay State Park`,
`Shine Tidelands State Park`,
`Skagit Island State Park`,
`Skull Island State Park`,
`South Whidbey Island State Park`,
`Spencer Spit State Park`,
`Spring Creek Hatchery State Park`,
`Squak Mountain State Park`,
`Squilchuck State Park`,
`Steamboat Rock State Park`,
`Steptoe Battlefield State Park`,
`Steptoe Butte State Park`,
`Stretch Point State Park`,
`Stuart Island State Park`,
`Sucia Island State Park`,
`Sun Lakes-Dry Falls State Park`,
`Tolmie State Park`,
`Triton Cove State Park`,
`Turn Island State Park`,
`Twanoh State Park`,
`Twenty-Five Mile Creek State Park`,
`Twin Harbors State Park`,
`Wallace Falls State Park`,
`Wenatchee Confluence State Park`,
`Westhaven State Park`,
`Westport Light State Park`,
`Yakima Sportsman State Park`,
`Audra State Park`,
`Babcock State Park`,
`Beartown State Park`,
`Beech Fork State Park`,
`Berkeley Springs State Park`,
`Blackwater Falls State Park`,
`Blennerhassett State Park`,
`Island Historical State Park`,
`Bluestone State Park`,
`Cacapon Resort State Park`,
`Camp Creek[g] State Park`,
`Canaan Valley State Park`,
`Resort State Park`,
`Carnifex Ferry State Park`,
`Battlefield State Park`,
`Cass Scenic State Park`,
`Railroad State Park`,
`Cathedral State Park`,
`Cedar Creek State Park`,
`Chief Logan[h] State Park`,
`Droop Mountain State Park`,
`Battlefield State Park`,
`Fairfax Stone State Park`,
`Historical State Park`,
`Monument State Park`,
`Greenbrier River State Park`,
`Trail State Park`,
`Hawks Nest State Park`,
`Holly River State Park`,
`Little Beaver State Park`,
`Lost River State Park`,
`Moncove Lake State Park`,
`North Bend State Park`,
`North Bend State Park`,
`Rail Trail State Park`,
`Pinnacle Rock State Park`,
`Pipestem Resort State Park`,
`Prickett's Fort State Park`,
`Stonewall Jackson State Park`,
`Lake State Park`,
`Tomlinson Run State Park`,
`Tu-Endie-Wei State Park`,
`Twin Falls Resort State Park`,
`Tygart Lake State Park`,
`Valley Falls State Park`,
`Watoga State Park`,
`Watters Smith State Park`,
`Amnicon Falls State Park`,
`Aztalan State Park`,
`Belmont Mound State Park`,
`Big Bay State Park`,
`Big Foot Beach State Park`,
`Blue Mound State Park`,
`Brunet Island State Park`,
`Buckhorn State Park`,
`Cadiz Springs State Recreation Area`,
`Campbellsport Drumlins State Park`,
`Capital Springs State Recreation Area`,
`Chippewa Moraine State Recreation Area`,
`Copper Culture State Park`,
`Copper Falls State Park`,
`Council Grounds State Park`,
`Cross Plains State Park`,
`Devil's Lake State Park`,
`Fischer Creek State Recreation Area`,
`Grand Traverse Island State Park`,
`Governor Dodge State Park`,
`Governor Nelson State Park`,
`Governor Thompson State Park`,
`Harrington Beach State Park`,
`Hartman Creek State Park`,
`Heritage Hill State Historical Park`,
`High Cliff State Park`,
`Hoffman Hills State Recreation Area`,
`Holzhueter Farm Conservation Park`,
`Interstate State Park`,
`Kinnickinnic State Park`,
`Kohler-Andrae State Park`,
`Lake Kegonsa State Park`,
`Lake Wissota State Park`,
`Lakeshore State Park`,
`Menominee River State Park and Recreation Area`,
`Merrick State Park`,
`Mill Bluff State Park`,
`Mirror Lake State Park`,
`Natural Bridge State Park`,
`Nelson Dewey State Park`,
`New Glarus Woods State Park`,
`Newport State Park`,
`Pattison State Park`,
`Peninsula State Park`,
`Perrot State Park`,
`Potawatomi State Park`,
`Rib Mountain State Park`,
`Richard Bong State Recreation Area`,
`Roche-a-Cri State Park`,
`Rock Island State Park`,
`Rocky Arbor State Park`,
`Straight Lake State Park`,
`Tower Hill State Park`,
`Whitefish Dunes State Park`,
`Wildcat Mountain State Park`,
`Willow River State Park`,
`Wyalusing State Park`,
`Yellowstone Lake State Park`,
`Bear River State Park`,
`Boysen State Park`,
`Buffalo Bill State Park`,
`Curt Gowdy State Park`,
`Edness K. Wilkins State Park`,
`Glendo State Park`,
`Guernsey State Park`,
`Hawk Springs State Recreation Area`,
`Hot Springs State Park`,
`Keyhole State Park`,
`Seminoe State Park`,
`Sinks Canyon State Park`,
`Ames Monument`,
`Camp Douglas Officers’ Club`,
`Connor Battlefield`,
`Fort Bonneville`,
`Fort Bridger`,
`Fort Fetterman`,
`Fort Fred Steele`,
`Fort Phil Kearny`,
`Fort Reno`,
`Granger Stage Station`,
`Historic Governors' Mansion`,
`Independence Rock`,
`Legend Rock State Archaeological Site`,
`Medicine Lodge State Archaeological Site`,
`Names Hill`,
`Oregon Trail Ruts`,
`Piedmont Charcoal Kilns`,
`Platte River Crossing`,
`Point of Rocks Stage Station`,
`Register Cliff`,
`South Pass City`,
`Woodruff Cabin Site`,
`Wyoming Pioneer Museum`,
`Wyoming Territorial Prison`];

async function dummy() {
    txt_str = "";
    for (let i = 0; i < nameArray.length; i++) {
        await geocode(nameArray[i]);
    }
    fs.writeFileSync('/Users/msheslow/mapper/latLng2',txt_str);
}

dummy();