const axios = require('axios');

async function geocode(name) {
    try {
        await axios.get('https://maps.googleapis.com/maps/api/geocode/json', {
            params: {
                address: name,
                key: 'AIzaSyBhcNo_EDGsF_lGfThVgAVtweh_DlciUCQ'
            }
        })
        .then(function(response) {
            let lat = response.data.results[0].geometry.location.lat;
            let lng = response.data.results[0].geometry.location.lng;
            let latLngOutput = name + "," + lat + "," + lng;
            console.log(latLngOutput);
        })
    } catch (err) {
        console.log(err);
    }
    return;
}

let nameArray = [`Birmingham Civil Rights National Monument`,
`Freedom Riders National Monument`,
`Horseshoe Bend National Military Park`,
`Little River Canyon National Preserve`,
`Russell Cave National Monument`,
`Tuskegee Airmen National Historic Site`,
`Tuskegee Institute National Historic Site`,
`Alagnak Wild River`,
`Aniakchak National Monument`,
`Aniakchak National Preserve`,
`Bering Land Bridge National Preserve`,
`Cape Krusenstern National Monument`,
`Denali National Park`,
`Denali National Preserve`,
`Gates of the Arctic National Park`,
`Gates of the Arctic National Preserve`,
`Glacier Bay National Park`,
`Glacier Bay National Preserve`,
`Katmai National Park`,
`Katmai National Preserve`,
`Kenai Fjords National Park`,
`Klondike Gold Rush National Historical Park`,
`Kobuk Valley National Park`,
`Lake Clark National Park`,
`Lake Clark National Preserve`,
`Noatak National Preserve`,
`Sitka National Historical Park`,
`Wrangell-St. Elias National Park`,
`Wrangell-St. Elias National Preserve`,
`Yukon-Charley Rivers National Preserve`,
`National Park of American Samoa`,
`Canyon De Chelly National Monument`,
`Casa Grande Ruins National Monument`,
`Chiricahua National Monument`,
`Coronado National Memorial`,
`Fort Bowie National Historic Site`,
`Glen Canyon National Recreation Area`,
`Grand Canyon National Park`,
`Hohokam Pima National Monument`,
`Hubbell Trading Post National Historic Site`,
`Montezuma Castle National Monument`,
`Navajo National Monument`,
`Organ Pipe Cactus National Monument`,
`Petrified Forest National Park`,
`Pipe Spring National Monument`,
`Saguaro National Park`,
`Sunset Crater Volcano National Monument`,
`Tonto National Monument`,
`Tumacacori National Historical Park`,
`Tuzigoot National Monument`,
`Walnut Canyon National Monument`,
`Wupatki National Monument`,
`Arkansas Post National Memorial`,
`Buffalo National River`,
`Fort Smith National Historic Site`,
`Hot Springs National Park`,
`Little Rock Central High School National Historic Site`,
`Pea Ridge National Military Park`,
`President William Jefferson Clinton Birthplace Home National Historic Site`,
`Cabrillo National Monument`,
`Castle Mountains National Monument`,
`César E. Chávez National Monument`,
`Channel Islands National Park`,
`Death Valley National Park`,
`Devils Postpile National Monument`,
`Eugene O'Neill National Historic Site`,
`Fort Point National Historic Site`,
`Golden Gate National Recreation Area`,
`John Muir National Historic Site`,
`Joshua Tree National Park`,
`Kings Canyon National Park`,
`Lassen Volcanic National Park`,
`Lava Beds National Monument`,
`Manzanar National Historic Site`,
`Mojave National Preserve`,
`Muir Woods National Monument`,
`Pinnacles National Park`,
`Point Reyes National Seashore`,
`Port Chicago Naval Magazine National Memorial`,
`Redwood National Park`,
`Rosie the Riveter World War II Home Front National Historical Park`,
`San Francisco Maritime National Historical Park`,
`Santa Monica Mountains National Recreation Area`,
`Sequoia National Park`,
`Tule Lake National Monument`,
`Whiskeytown-Shasta-Trinity National Recreation Area`,
`Yosemite National Park`,
`Bent's Old Fort National Historic Site`,
`Black Canyon of the Gunnison National Park`,
`Colorado National Monument`,
`Curecanti National Recreation Area`,
`Dinosaur National Monument`,
`Florissant Fossil Beds National Monument`,
`Great Sand Dunes National Park`,
`Great Sand Dunes National Preserve`,
`Hovenweep National Monument`,
`Mesa Verde National Park`,
`Rocky Mountain National Park`,
`Sand Creek Massacre National Historic Site`,
`Yucca House National Monument`,
`Weir Farm National Historic Site`,
`First State National Historical Park`,
`Big Cypress National Preserve`,
`Biscayne National Park`,
`Canaveral National Seashore`,
`Castillo de San Marcos National Monument`,
`De Soto National Memorial`,
`Dry Tortugas National Park`,
`Everglades National Park`,
`Fort Caroline National Memorial`,
`Fort Matanzas National Monument`,
`Gulf Islands National Seashore`,
`Timucuan Ecological and Historic Preserve`,
`Andersonville National Historic Site`,
`Chattahoochee River National Recreation Area`,
`Chickamauga & Chattanooga National Military Park`,
`Cumberland Island National Seashore`,
`Fort Frederica National Monument`,
`Fort Pulaski National Monument`,
`Jimmy Carter National Historic Site`,
`Kennesaw Mountain National Battlefield Park`,
`Martin Luther King, Jr. National Historic Site`,
`Ocmulgee Mounds National Historical Park`,
`War in the Pacific National Historical Park`,
`Haleakala National Park`,
`Hawaii Volcanoes National Park`,
`Honouliuli National Historic Site`,
`Kalaupapa National Historical Park`,
`Kaloko-Honokohau National Historical Park`,
`Pearl Harbor National Memorial`,
`Pu'uhonua O Honaunau National Historical Park`,
`Pu'ukohola Heiau National Historic Site`,
`City of Rocks National Reserve`,
`Craters of the Moon National Monument`,
`Craters of the Moon National Preserve`,
`Hagerman Fossil Beds National Monument`,
`Minidoka National Historic Site`,
`Nez Perce National Historical Park`,
`Lincoln Home National Historic Site`,
`Pullman National Monument`,
`George Rogers Clark National Historical Park`,
`Indiana Dunes National Park`,
`Lincoln Boyhood National Memorial`,
`Effigy Mounds National Monument`,
`Herbert Hoover National Historic Site`,
`Brown v. Board of Education National Historic Site`,
`Fort Larned National Historic Site`,
`Fort Scott National Historic Site`,
`Nicodemus National Historic Site`,
`Tallgrass Prairie National Preserve`,
`Abraham Lincoln Birthplace National Historical Park`,
`Camp Nelson Heritage National Monument`,
`Cumberland Gap National Historical Park`,
`Mammoth Cave National Park`,
`Mill Springs Battlefield National Monument`,
`Cane River Creole National Historical Park`,
`Jean Lafitte National Historical Park and Preserve`,
`New Orleans Jazz National Historical Park`,
`Poverty Point National Monument`,
`Acadia National Park`,
`Appalachian National Scenic Trail`,
`Katahdin Woods and Waters National Monument`,
`Saint Croix Island International Historic Site`,
`Antietam National Battlefield`,
`Assateague Island National Seashore`,
`Catoctin Mountain Park`,
`Chesapeake and Ohio Canal National Historical Park`,
`Clara Barton National Historic Site`,
`Fort McHenry National Monument and Historic Shrine`,
`Fort Washington Park`,
`Greenbelt Park`,
`Hampton National Historic Site`,
`Harriet Tubman Underground Railroad National Historical Park`,
`Monocacy National Battlefield`,
`Piscataway Park`,
`Potomac Heritage National Scenic Trail`,
`Thomas Stone National Historic Site`,
`Adams National Historical Park`,
`Boston African American National Historic Site`,
`Boston Harbor Islands National Recreation Area`,
`Boston National Historical Park`,
`Cape Cod National Seashore`,
`Frederick Law Olmsted National Historic Site`,
`John F. Kennedy National Historic Site`,
`Longfellow House–Washington's Headquarters National Historic Site`,
`Lowell National Historical Park`,
`Minute Man National Historical Park`,
`New Bedford Whaling National Historical Park`,
`Salem Maritime National Historic Site`,
`Saugus Iron Works National Historic Site`,
`Springfield Armory National Historic Site`,
`Isle Royale National Park`,
`Keweenaw National Historical Park`,
`Pictured Rocks National Lakeshore`,
`River Raisin National Battlefield Park`,
`Sleeping Bear Dunes National Lakeshore`,
`Grand Portage National Monument`,
`Mississippi National River and Recreation Area`,
`Pipestone National Monument`,
`Voyageurs National Park`,
`Brices Cross Roads National Battlefield Site`,
`Natchez National Historical Park`,
`Natchez Trace Parkway`,
`Natchez Trace National Scenic Trail`,
`Tupelo National Battlefield`,
`Vicksburg National Military Park`,
`Gateway Arch National Park`,
`George Washington Carver National Monument`,
`Harry S Truman National Historic Site`,
`Ozark National Scenic Riverways`,
`Ste. Genevieve National Historical Park`,
`Ulysses S. Grant National Historic Site`,
`Wilson's Creek National Battlefield`,
`Big Hole National Battlefield`,
`Bighorn Canyon National Recreation Area`,
`Glacier National Park`,
`Grant-Kohrs Ranch National Historic Site`,
`Little Bighorn Battlefield National Monument`,
`Agate Fossil Beds National Monument`,
`Homestead National Monument of America`,
`Missouri National Recreational River`,
`Niobrara National Scenic River`,
`Scotts Bluff National Monument`,
`Great Basin National Park`,
`Lake Mead National Recreation Area`,
`Tule Springs Fossil Beds National Monument`,
`Saint-Gaudens National Historical Park`,
`Delaware Water Gap National Recreation Area`,
`Great Egg Harbor Scenic and Recreational River`,
`Morristown National Historical Park`,
`Paterson Great Falls National Historical Park`,
`Thomas Edison National Historical Park`,
`Aztec Ruins National Monument`,
`Bandelier National Monument`,
`Capulin Volcano National Monument`,
`Carlsbad Caverns National Park`,
`Chaco Culture National Historical Park`,
`El Malpais National Monument`,
`El Morro National Monument`,
`Fort Union National Monument`,
`Gila Cliff Dwellings National Monument`,
`Manhattan Project National Historical Park`,
`Pecos National Historical Park`,
`Petroglyph National Monument`,
`Salinas Pueblo Missions National Monument`,
`Valles Caldera National Preserve`,
`White Sands National Park`,
`African Burial Ground National Monument`,
`Castle Clinton National Monument`,
`Eleanor Roosevelt National Historic Site`,
`Federal Hall National Memorial`,
`Fire Island National Seashore`,
`Fort Stanwix National Monument`,
`Gateway National Recreation Area`,
`General Grant National Memorial`,
`Governors Island National Monument`,
`Hamilton Grange National Memorial`,
`Harriet Tubman National Historical Park`,
`Home of Franklin D. Roosevelt National Historic Site`,
`Martin Van Buren National Historic Site`,
`Saint Paul's Church National Historic Site`,
`Sagamore Hill National Historic Site`,
`Saratoga National Historical Park`,
`Statue of Liberty National Monument`,
`Stonewall National Monument`,
`Theodore Roosevelt Birthplace National Historic Site`,
`Theodore Roosevelt Inaugural National Historic Site`,
`Vanderbilt Mansion National Historic Site`,
`Women's Rights National Historical Park`,
`Blue Ridge Parkway`,
`Cape Hatteras National Seashore`,
`Cape Lookout National Seashore`,
`Carl Sandburg Home National Historic Site`,
`Fort Raleigh National Historic Site`,
`Guilford Courthouse National Military Park`,
`Moores Creek National Battlefield`,
`Wright Brothers National Memorial`,
`Fort Union Trading Post National Historic Site`,
`Knife River Indian Villages National Historic Site`,
`Theodore Roosevelt National Park`,
`Charles Young Buffalo Soldiers National Monument`,
`Cuyahoga Valley National Park`,
`Dayton Aviation Heritage National Historical Park`,
`First Ladies National Historic Site`,
`Hopewell Culture National Historical Park`,
`James A. Garfield National Historic Site`,
`Perry's Victory and International Peace Memorial`,
`William Howard Taft National Historic Site`,
`Chickasaw National Recreation Area`,
`Washita Battlefield National Historic Site`,
`Crater Lake National Park`,
`Lewis and Clark National Historical Park`,
`John Day Fossil Beds National Monument`,
`Oregon Caves National Monument and Preserve`,
`Allegheny Portage Railroad National Historic Site`,
`Edgar Allan Poe National Historic Site`,
`Eisenhower National Historic Site`,
`Flight 93 National Memorial`,
`Fort Necessity National Battlefield`,
`Friendship Hill National Historic Site`,
`Gettysburg National Military Park`,
`Hopewell Furnace National Historic Site`,
`Independence National Historical Park`,
`Johnstown Flood National Memorial`,
`Middle Delaware National Scenic River`,
`Steamtown National Historic Site`,
`Thaddeus Kosciuszko National Memorial`,
`Upper Delaware Scenic and Recreational River`,
`Valley Forge National Historical Park`,
`San Juan National Historic Site`,
`Blackstone River Valley National Historical Park`,
`Roger Williams National Memorial`,
`Charles Pinckney National Historic Site`,
`Congaree National Park`,
`Cowpens National Battlefield`,
`Fort Sumter and Fort Moultrie National Historical Park`,
`Kings Mountain National Military Park`,
`Ninety Six National Historic Site`,
`Reconstruction Era National Historical Park`,
`Badlands National Park`,
`Jewel Cave National Monument`,
`Minuteman Missile National Historic Site`,
`Mount Rushmore National Memorial`,
`Wind Cave National Park`,
`Andrew Johnson National Historic Site`,
`Big South Fork National River and Recreation Area`,
`Fort Donelson National Battlefield`,
`Great Smoky Mountains National Park`,
`Obed Wild and Scenic River`,
`Shiloh National Military Park`,
`Stones River National Battlefield`,
`Alibates Flint Quarries National Monument`,
`Amistad National Recreation Area`,
`Big Bend National Park`,
`Big Thicket National Preserve`,
`Chamizal National Memorial`,
`Fort Davis National Historic Site`,
`Guadalupe Mountains National Park`,
`Lake Meredith National Recreation Area`,
`Lyndon B. Johnson National Historical Park`,
`Padre Island National Seashore`,
`Palo Alto Battlefield National Historical Park`,
`Rio Grande Wild and Scenic River`,
`San Antonio Missions National Historical Park`,
`Waco Mammoth National Monument`,
`Arches National Park`,
`Bryce Canyon National Park`,
`Canyonlands National Park`,
`Capitol Reef National Park`,
`Cedar Breaks National Monument`,
`Golden Spike National Historical Park`,
`Natural Bridges National Monument`,
`Rainbow Bridge National Monument`,
`Timpanogos Cave National Monument`,
`Zion National Park`,
`Marsh-Billings-Rockefeller National Historical Park`];

async function dummy() {
    for (let i = 0; i < nameArray.length; i++) {
        await geocode(nameArray[i]);
    }
}